### ISSUE TITLE
[Bug] Error :   _UnityARKit_Camera_GetTextureReleaseCallbackHandle

### ISSUE THREAD

**Issue by hasionerin** [Unity-Technologies/arfoundation-samples#1036]
when i update ARFoundation version to 4.2.6 , Xcode 13.4 build error :
"Undefined symbol: _UnityARKit_Camera_GetTextureReleaseCallbackHandle "
@ankur-unity

**Comment by hasionerin** [comment]
both  ARFoundation and  ARKit XR Plugin have already update to 4.2.6 , also the same error

**Comment by ankur-unity** [comment]
If you haven't already, try cleaning the Xcode project that Unity generated before you did the update. Unity might be keeping some of the files from previous build which could interfere with the current build.

I also recommend using version 4.2.7 which is the latest patch. Version 4.2.6 had couple of critical issues which we fixed in 4.2.7 patch. You will need to use Xcode 14.0 or higher with 4.2.7.

https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.2/changelog/CHANGELOG.html#changed

**Comment by loreleip** [comment]
I had the same problem when XCode suddenly upgraded itself, this XCode error message appeared when trying to do iOS Unity AR builds to my iPhone. It was finally solved when I upgraded my Unity Editor to the most current version, 2021.3.16f1.

**Comment by ankur-unity** [comment]
Thanks for the tip, @loreleip.

The native symbol `_UnityARKit_Camera_GetTextureReleaseCallbackHandle` existed in AR Foundation 4.2.6 and was removed in 4.2.7. After updating to the new AR Foundation and ARKit 4.2.7 patches, remove the previous Unity generated Xcode project to avoid this issue. Updating the Unity Editor might have just cleaned/overwritten the cache of compiled libraries resolving the problem.

Closing this issue due to lack of response on the user after it has been answered above. Feel free to reopen it or open another issue, if the issue persist.
