### ISSUE TITLE
Making a 3D scanner

### ISSUE THREAD

**Issue by moheydy** [Unity-Technologies/arfoundation-samples#1050]
It's been almost 2 years and we apply every time but no effect.

For AR and VR and Metaverse projects, it is very important to be able to design a 3D model of real objects inside them, so that it can be sold or used for other purposes.

I think there is currently the technology for it using Lidar, DepthAPi ARcore and OpenAI, but there are no tutorials or examples ready.  I hope you understand how effective such a feature can be in the creativity and design of programs.

I hope the unity team will add this feature...

**Comment by moheydy** [comment]
Sorry Open3D, not OpenAI

**Comment by andyb-unity** [comment]
From our [docs](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/index.html):

The AR Foundation package contains interfaces for AR features, but doesn't implement any features itself. To use AR Foundation on a target platform, you also need a separate provider plug-in package for that platform.

Unity officially supports the following provider plug-ins:

[Google ARCore XR Plug-in](https://docs.unity3d.com/Packages/com.unity.xr.arcore@5.0/manual/index.html) on Android
[Apple ARKit XR Plug-in](https://docs.unity3d.com/Packages/com.unity.xr.arkit@5.0/manual/index.html) on iOS
[OpenXR Plug-in](https://docs.unity3d.com/Packages/com.unity.xr.openxr@1.5/manual/index.html) on HoloLens 2

Neither ARKit, ARCore, nor OpenXR have a 3D object mesh generation API.

If you are looking for raw mesh output from compatible AR platforms, see our [Meshing](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/features/meshing.html) documentation.

Otherwise you are welcome to use a third-party tool to either scan meshes and import them into Unity, and/or incorporate object scanning into your own app.

**Comment by andyb-unity** [comment]
I wanted to add on to my previous response.

While AR Foundation will not integrate 3D object mesh scanning for the reasons I describe above, there are options available to you now from Apple and Unity.

Apple offers the Object Capture API: https://developer.apple.com/augmented-reality/object-capture/, which is not part of ARKit but available for you to use if you like.

Unity offers an integration of Apple's Object Capture API in our AR Companion App, which you can use to scan environments and objects and integrate those scans into your workflow: https://blog.unity.com/technology/the-ar-companion-app-is-now-available

Hope that helps.

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open this issue if you have further questions.

**Comment by yosun** [comment]
@andyb-unity  why not release the ar-companion app source so that people can integrate 3d scanning into their unity games at runtime (instead of in-editor only)

**Comment by yosun** [comment]
also there used to be an Object scanning app that came with Unity's ARKit
