### ISSUE TITLE
Multi user support with AR foundation /AR Kit to sync game objects transform

### ISSUE THREAD

**Issue by Nishat11** [Unity-Technologies/arfoundation-samples#1098]
How to sync game-object's (Spawn/placed game-object in an AR environment) transform to all my connected app instances? 

Hello, I am using AR Foundation 5 with ARKit 5. I am looking for a multiuser functionality using ARFoundation and AR collaboration. Is there any way I can sync game-object's (Spawn/placed game-object in an AR environment) transform to all my connected app instances? 

If not then, is there any plan or other solution available to make a multiuser/ trackable game object in an AR environment?

**Comment by andyb-unity** [comment]
We don't have a sample currently that does what you describe. AR Foundation has no opinion on networking-- you could use any multiplayer solution such as Unity's NetCode for GameObjects to accomplish transform synchronization between devices.

There is a team working on a multiplayer sample at the moment, but it won't be ready any time soon.

**Comment by andyb-unity** [comment]
Closing this issue as asked and answered. Feel free to re-open it if you have further questions.

**Comment by anuzk13** [comment]
Hi! I was wondering if the example you mention is [this one](https://github.com/Unity-Technologies/arfoundation-samples/tree/main/Assets/Scenes/ARKit/ARCollaborationData) and if any examples work for Android?

**Comment by andyb-unity** [comment]
Since my last reply in 2023, Unity has released some multiplayer sample projects:
* [VR Multiplayer Template](https://docs.unity3d.com/Packages/com.unity.template.vr-multiplayer@2.0/manual/index.html)
* [Mixed Reality Multiplayer Tabletop Template](https://docs.unity3d.com/Packages/com.unity.template.mr-multiplayer@1.0/manual/index.html)

You would need to modify these projects to work with ARCore. Unity does not provide any multiplayer code samples for ARCore, but again you could use any networking solution of your choice in your project.
