### ISSUE TITLE
[ARFoundation 6.0 with Unity 2022.3.15f1] error CS0246: The type or namespace name 'IAnalytic' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by vaoliva** [Unity-Technologies/arfoundation-samples#1166]
Opening project on main branch agains Unity 2022.3.15f1 gives a few reference issues e.g. 
: ### **Library\PackageCache\com.unity.xr.arfoundation@6.0.0-pre.6\Editor\ARAnalytics\AREditorAnalyticsEvent.cs(20,43): error CS0246: The type or namespace name 'IAnalytic' could not be found (are you missing a using directive or an assembly reference?)**

**Comment by andyb-unity** [comment]
AR Foundation 6.0 is not compatible with Unity 2022.3. The minimum version of Unity required to use AR Foundation 6 is 2023.3 as specified in the docs: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@6.0/manual/project-setup/install-arfoundation.html. This is necessary because we built new functionality that depends on new features in Unity 2023.
