### ISSUE TITLE
Anchor fixed position of the object (SimpleAR) when clicking through another location

### ISSUE THREAD

**Issue by NGUYENTRUONGKHANH** [Unity-Technologies/arfoundation-samples#143]
I have used SimpleAR in the AR foundation. After selecting the position of an object on the plane. Every time I press another plane, the position of the object changes. How can I Anchor fixed that position, not allow it to change position every time I click elsewhere. I struggled for days but failed. Looking forward to the guidance. Thank you so much community!

**Comment by tdmowrer** [comment]
I think you want to modify the [`PlaceOnPlace.cs`](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scripts/PlaceOnPlane.cs) script. The current logic does a raycast each frame and if the object has not been placed, it instantiates it at the hit position, otherwise it will move it to that position. [These lines](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scripts/PlaceOnPlane.cs#L75-L78) correspond to the "otherwise, move to that position" logic. Simply remove them to place the object at the first hit position and keep it there.

If your goal is to have the user move the object around until they pick up their finger for the first time, you can use "touch phases" to detect this. [`TouchPhase.Ended`](https://docs.unity3d.com/ScriptReference/TouchPhase.html) will tell you when the user picks up their finger.

**Comment by NGUYENTRUONGKHANH** [comment]
I have fixed this error by creating a UI, thank you very much for the advice!
