### ISSUE TITLE
Linux Support arfoundation-samples

### ISSUE THREAD

**Issue by Stefjs** [Unity-Technologies/arfoundation-samples#195]
Ubuntu 18.04
Unity 2019.1.9f1
ARCore XR PLugin Version 2.1.0

Unity Hub -> New -> Unity -> Package Manager -> Install ARCore XR Plugin -> Errors

Errors:
> Library/PackageCache/com.unity.xr.arcore@2.1.0-preview.5/Editor/ARCoreBuildProcessor.cs(220,81): error CS0103: The name 'platformName' does not exist in the current context

> Library/PackageCache/com.unity.xr.arcore@2.1.0-preview.5/Editor/ARCoreBuildProcessor.cs(220,109): error CS0103: The name 'extension' does not exist in the current context

**Comment by vincentfretin** [comment]
Hi @Stefjs 
I installed Unity on Ubuntu 18.04 as well and got the same error.
ARFoundation doesn't seem to support Linux yet. The arcoreimg binary is only available for Windows and MacOS plateforms.

Library/PackageCache/com.unity.xr.arcore@2.1.0-preview.5/Tools~/
├── MacOS
│   └── arcoreimg
└── Windows
    └── arcoreimg.exe

If you don't need ARCore Image tracking, what you can do to not have the error is to go in the Other Settings panel of the Player settings and navigate to the Scripting Define Symbols text box. and write UNITY_EDITOR_OSX there. I build a simple AR app this way. I installed Android Studio to install Android SDK as well, because the Android SDK bundled with Unity on Linux doesn't work at all for me.

I tried to modify " Library/PackageCache/com.unity.xr.arcore@2.1.0-preview.5/Editor/ARCoreBuildProcessor.cs" to add some condition for UNITY_EDITOR_LINUX (I saw somewhere in the forum that this define should be defined on Linux) but when I build, this revert the change. Does somebody know how to copy the dependency in the project to be able to customize it? I'm new to Unity and I don't know much about the package manager.

**Comment by vincentfretin** [comment]
FYI, ARCore SDK for Android v1.10 https://github.com/google-ar/arcore-android-sdk/releases does support Linux. There is a linux/arcoreimg binary in arcore-android-sdk-1.10.0/tools/arcoreimg/

**Comment by Stefjs** [comment]
@vincentfretin Thanks for the Scripting Define Symbols tip, I just tried it and I can finally run the examples.

**Comment by vincentfretin** [comment]
com.unity.xr.arcore@2.2.0-preview.2/Tools~/ still has only MacOS Windows. No Linux.

**Comment by ardiya** [comment]
Running into the same issue.
Could we rename this issue into "Linux Support arfoundation-samples" @Stefjs?

**Comment by vincentfretin** [comment]
I just saw the Linux support was added in [2.2.0-preview.6] - 2019-10-23
https://docs.unity3d.com/Packages/com.unity.xr.arcore@2.2/changelog/CHANGELOG.html
I didn't test it though, I don't need the feature in my project.
