### ISSUE TITLE
VertexChangeThreshold on ARPlane isn't implemented

### ISSUE THREAD

**Issue by HawkenKing** [Unity-Technologies/arfoundation-samples#196]
You can change the VertexChangeThreshold to any number and it has no effect on the plane, from 0.01 to 50, it behaves the same way when absorbing new points and changing boundary size. This variable doesn't appear to be applied.

**Comment by tdmowrer** [comment]
The [vertexChangedThreshold](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARPlane.html#UnityEngine_XR_ARFoundation_ARPlane_vertexChangedThreshold) controls by how much a vertex in a plane's set of boundary vertices must have changed with respect to their previous positions to be considered "changed" (which triggers mesh regeneration).

There are, however, other conditions in which the boundary may be considered to have changed. For instance, if the number of vertices is different, then we can't compare the previous set with the current set because they are completely different.

I tried setting the value to 50, as you suggested, and confirmed that the points only change when the _number_ of points is different.
