### ISSUE TITLE
(Android) IL2CPP scripting backend seems to be not supported

### ISSUE THREAD

**Issue by FejZa** [Unity-Technologies/arfoundation-samples#26]
I tried building an Arfoundation android sample with IL2CPP and it did not ask for camera permissions at all and hence failed. Once I changed to Mono scripting backend and re-deployed, it asked for permission.

**Comment by timm-unity** [comment]
There is a bug in Unity where IL2CPP strips the entire ARCore assembly when it shouldn't. That will be fixed in a future update, but for now you can workaround this by adding a `link.xml` file to your Assets folder. We do this in the samples project, and you can just copy this file:

https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/link.xml

**Comment by timm-unity** [comment]
I just tested pulling a fresh copy of this repo and deployed it to a Pixel using IL2CPP. Works as expected (including the prompt for camera permission), so I suspect you're just missing the `link.xml`.

**Comment by FejZa** [comment]
Thanks! Totally missed that file.

**Comment by FejZa** [comment]
Hi. Has this issue been fixed by now? So I can close the issue.

**Comment by tdmowrer** [comment]
The `link.xml` workaround is no longer necessary.
