### ISSUE TITLE
Missing Scripts?

### ISSUE THREAD

**Issue by joleong** [Unity-Technologies/arfoundation-samples#265]
Missing (Mono Script)
Trying to run the examples in AR Foundation. In the ImageTracking and ObjectTracking scenes, the AR Session prefab is showing a missing (Mono Script).

ImageTracking example still builds and runs, but with ObjectTracking, the objects are not being detected.

**Comment by TeorikDeli** [comment]
Because ObjectTracking is removed in the latest ARFoundation 🤷🏻‍♂️ It was working stable in my opinion, but Unity says it was experimental. I believe you can use it with 2.2 (with beta iOS and beta Xcode). I don't know why they believe object tracking is the iOS 13 feature, because it isn't (It's iOS 12 feature). Maybe I understood wrong, I don't know 🤷🏻‍♂️

https://github.com/Unity-Technologies/arfoundation-samples/issues/240

**Comment by tdmowrer** [comment]
It's not an iOS 13 feature nor is it considered experimental by Apple. However, object tracking relies on experimental Unity APIs (i.e., something in the `UnityEngine.Experimental` namespace). The rules for verified packages require that no experimental APIs be used, so it was removed from the verified 2.1 package.
