### ISSUE TITLE
Occasional 45 degree tilt when using ARHumanBody.pose.rotation

### ISSUE THREAD

**Issue by magik-chorne** [Unity-Technologies/arfoundation-samples#278]
Hiya!
Unity 2019.1.5f
ARfoundation 2.2
iOS/xcode beta 5

I'm posing my model using ARHumanBody.pose.rotation and roughly 30% of the time I'm seeing a pose from ARFoundation/ARKit that looks like this in unity:
![tilt](https://user-images.githubusercontent.com/40373033/63807991-bf9e7b80-c8d3-11e9-95b2-807014775fd0.JPG)

We call it the "tilt". A weird 45 degree rotation of the character (usually away from the camera). I'm correctly posing the root and the hips - there doesn't seem to be any compensation embedded in those values. Similarly, when I remove the pose.rotation the tilt goes away (but of course - so does any body rotation).

I'm wondering - Is this a bug? Is this an issue with my implementation - like an up vector that I'm supposed to compensate with? Are others seeing this? I tried to use the ARFoundation samples as a guide, but they don't seem to be using arhumanbody.pose at all. Thanks

**Comment by magik-chorne** [comment]
@DavidMohrhardt 

I realized that the tilt seems to always be happening TOWARD or AWAY from the camera. It's not noticeable unless you do a 90 degree offset rotation - which is something regularly done in my app - but not really done in most of the apps/demos ive seen so far.

Try adding a local 90 degree rotation to "newSkeletonGO" in your script and you should see the same issue that I'm seeing.

**Comment by DavidMohrhardt** [comment]
No, the human body transform vs the pose is more a matter of ensuring that the transforms are applied in the expected space relative to the session origin since everything reported by the device is in session space.  The transform ensures this by the nature of its instantiation but the pose can be a little more picky if you are not placing it correctly.  I doubt this is the issue since the photo you provided seems to assert it is at least positionally correct.

As for the rotation, what is the direction and the circumstances of the rotation?  It seems odd that would have an effect on it especially given that the actual pose itself was reported as jumping the last time this issue arose but it does cause me to think it may have something to do with it.

One thing I should say is that I notice odd turning at side profile views.  Basically the device is hitting a grey area where it doesn't know if the body is turned or just really narrow and it causes some odd rotations to occur.  This is especially apparent if your legs are overlapping.

**Comment by tdmowrer** [comment]
Hi @magik-chorne,

We haven't been able to reproduce this in any recent version of Xcode/iOS. Are you still experiencing the 45 degree tilt issue? It could be that it was just an artifact of the beta version.

**Comment by magik-chorne** [comment]
hey @tdmowrer - I've long since abandoned this project (mainly due to the tilting issue).

If you can't reproduce it - then there is a high likelihood that some assumption wasn't properly accounted for. A significant amount of code was written to handle different hip heights, hips not being at the origin, different spaces (Z-up vs Y-up, etc.), slightly different T-poses, and so forth. The rotation thing was the last bug I couldn't figure out.

So in closing - rather than a bug - maybe a sug: for Unity to provide an API where an arbitrary rig can be fed in and correctly animated with arkit-formatted animation data (meaning - I can feed in pre-recorded data or modulate the data in real-time - feed it into the API - and get the intended pose).

**Comment by tdmowrer** [comment]
Thanks for the suggestion. What you describe sounds like the more general problem of animation retargeting. That's a complex technology in itself, and fortunately Unity has some tools to help with that. See the documentation on [retargeting](https://docs.unity3d.com/Manual/Retargeting.html).

I'll add an issue to our backlog to make a sample for this.
