### ISSUE TITLE
Detected plane doesn't load correctly

### ISSUE THREAD

**Issue by sai891215** [Unity-Technologies/arfoundation-samples#279]
Hi,

I try to use the AR Foundation with Unity 2019.2.1f1 on an iPhone X iOS 13. I did exactly the same process as instruction. But the plane mesh does not load properly, instead, it is a jittering line. The issue wasn't there in the AR foundation sample project, but when I remove the package and re-install the AR Foundation Package, the same issue appears. 

So I assume there is some compatibility issue with AR Foundation, which wasn't clear to me. Please let me know if there is something I overlook.

[Here is the screenshot, you can see the plane becomes lines](https://drive.google.com/file/d/1IHWM5mkUEbeVWZ_L4pNTGSgJbmce61ww/view?usp=sharing)

Thanks,
Shengzhi

**Comment by Organwolf** [comment]
How have you set up your project? Have you added or changed anything with the AR Plane Default prefab used by the AR Plane Manager? Do I understand you correctly that is the sample project works while using the same version of Unity and AR Foundation?

**Comment by tdmowrer** [comment]
When this issue was reported, iOS 13 was in beta and plane detection did not work properly unless you were using exactly the same version of the Xcode 11 beta with which the ARKit XR Plugin package was compiled. Now that iOS 13.1 and Xcode 11 have been released, this should no longer be an issue.

I'll close this issue for now, but please reopen it if the problem continues.
