### ISSUE TITLE
Cloud Build issue - UnityARKit.a(EventSystem.o)' was built without full bitcode.

### ISSUE THREAD

**Issue by yosun** [Unity-Technologies/arfoundation-samples#285]
Just grabbed the latest v3 of the ARFoundation set.... but it seems that it was built without full bitcode - issues building using Unity Cloud Build

 ` ld: bitcode bundle could not be generated because  /Libraries/com.unity.xr.arkit/Runtime/iOS/Xcode1000/UnityARKit.a(EventSystem.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
473: ▸ clang: error`

**Comment by TimKoppers** [comment]
I'm having the same issue, both when using Cloud Build or making a local build (with XCode 10.3)  

`bitcode bundle could not be generated because '/Users/timbo/Projects/face-acting-xc5/Libraries/com.unity.xr.arkit/Runtime/iOS/Xcode1000/UnityARKit.a(TrackableProvider.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/timbo/Projects/face-acting-xc5/Libraries/com.unity.xr.arkit/Runtime/iOS/Xcode1000/UnityARKit.a' for architecture arm64`

**Comment by tdmowrer** [comment]
This should be fixed with 3.0.0-preview.2 (released today).
