### ISSUE TITLE
Deserial & Reading of Worldmaps SLOWER than in old ARKit

### ISSUE THREAD

**Issue by smxthereisonlyone** [Unity-Technologies/arfoundation-samples#291]
Hey,

using a device with **iOS 13** plus either a) **old** ARKit plugin vs b) ARFoundation package create **two different** read and write speeds von worldmaps although the relocalization speed and accuracy **is the same**. The older ARKit plugin being much faster. Sometimes ARFoundation deserializes for up to 1 minute. Why is that? @tdmowrer 

Thanks for any insight :)

**Comment by blurxs** [comment]
i'm using a device with ios13 as well. it takes quite long to load but not a minute. How much space do you scan?
 it even crashes sometimes for me. when I try to scan more than just the current floor but multiple rooms I can load the data afterwards but it crashes after a few seconds

**Comment by tdmowrer** [comment]
I suspect this to be a difference between iOS 12 and 13. The ARKit XR Plugin uses the same code as the [BitBucket plugin](https://bitbucket.org/Unity-Technologies/unity-arkit-plugin/src/94e47eae59546c1c824f1ebc345cedff21104259/Assets/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARWorldMap.mm#lines-55) to deserialize the ARWorldMap (just a call to [`NSKeyedUnarchiver`](https://developer.apple.com/documentation/foundation/nskeyedunarchiver)).

And because the ARKit XR Plugin operates on raw bytes instead of filenames, I would expect it to be faster, as loading a file from disk is not part of the API. What specific function call is slow? How are you timing it?

> it even crashes sometimes for me...I can load the data afterwards but it crashes after a few seconds

What is the callstack?

**Comment by tdmowrer** [comment]
Looks like our world map [sample](https://github.com/Unity-Technologies/arfoundation-samples/blob/master/Assets/Scripts/ARWorldMapController.cs#L177-L187) limits its file read to 10,240 bytes per frame, so if you have copied this method and are loading a large world map, it would be quite slow. This is just sample code -- it is up to you to obtain the bytes of the world map. 

A simple [File.ReadAllBytes](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readallbytes?view=netframework-4.8) would be much faster. However, this blocks the main thread while reading, which is why the sample only reads a small number of bytes per frame.

If [ARWorldMap.TryDeserialize](https://docs.unity3d.com/Packages/com.unity.xr.arkit@3.0/api/UnityEngine.XR.ARKit.ARWorldMap.html#UnityEngine_XR_ARKit_ARWorldMap_TryDeserialize_NativeArray_System_Byte__UnityEngine_XR_ARKit_ARWorldMap__) is indeed slow, please provide precise timing data along with the number of bytes deserialized.

**Comment by tdmowrer** [comment]
Closing issue as this seems to be an artifact of the sample code, which intentionally breaks up the file reading over multiple frames. Please reopen if it continues to be an issue.
