### ISSUE TITLE
ARHumanBodyManagar and ARFace not found 

### ISSUE THREAD

**Issue by Akash-1210** [Unity-Technologies/arfoundation-samples#302]
Hello, 
I implement Human body tracking system but it gives ARHumanBodyManagar and ARFace not found. I already add ARKit xr plugin, ar foundation, xr management. how can I solved this, 
use unity 2019.2.5

**Comment by AbrahamManomotion** [comment]
Same here

**Comment by janalexxxx** [comment]
Same here

**Comment by akshatgoel20** [comment]
Same here

**Comment by tdmowrer** [comment]
What exact versions of the packages, iOS, and Xcode are you using?

**Comment by kjyv** [comment]
Same here, after updating the packages ARFoundation, ARSubsystems and ARKit XR Plugin from 3.0.0-preview3 to 3.0.0 / 3.0.1 the class ARHumanBodyManager is not found anymore. The iOS and Xcode versions are likely irrelevant as this is a compile error with C#. For OP, I suppose ARFace has moved to the "ARKit Face Tracking" package, but that doesn't include Human Body tracking.

**Comment by ynaoto** [comment]
Same here ++

**Comment by tdmowrer** [comment]
Human body tracking was not deemed production ready, so it was removed from the verified package. It is available again in the 3.1 preview packages though, and occlusion support has been improved significantly.

Face tracking support on iOS has been in a separate package for some time (this is due to extra security restrictions imposed by Apple -- read more [here](https://developer.apple.com/documentation/arkit/arfacetrackingconfiguration)). However, `ARFace` has been a type in ARFoundation since the feature was introduced.

Please paste the exact errors you are getting.
