### ISSUE TITLE
ARKit plugin build error (ARM64) even with optional

### ISSUE THREAD

**Issue by Borisss** [Unity-Technologies/arfoundation-samples#318]
I have ARKit set as optional yet I cannot build for ARMv7, is that ok?

`BuildFailedException: ARKit XR Plugin only supports the ARM64 architecture. See Player Settings > Other Settings > Architecture.`

Aren't we losing a lot of older devices like this?

On Android, with ARCore as optional I can target both architectures...

ARFoundation 2.0.2, ARKit Plugin 2.0.1, Unity 2019.2

**Comment by tdmowrer** [comment]
The ARKit XR plugin only supports ARM64, and we have no plans to add support for ARMv7. The latest version of Unity no longer supports ARMv7 either.

**Comment by sergiosolorzano** [comment]
Hi @tdmowrer I released an app on apple app store with arfoundation in 2018 and with unity 2018.3.0f2 set universal architecture, info.plist UIRequiredDeviceCapabilities as shown below:

`<key>UIRequiredDeviceCapabilities</key>
    <array>
      <string>armv7</string>
      <string>metal</string>
      <string>arkit</string>
    </array>
`
I am now trying to update this app with Unity 2019.4.36f1 and I need to select ARM64 to avoid the above mentioned error. Apple will not let me update the app because the UIRequiredDeviceCapabilities are different, now:

`<key>UIRequiredDeviceCapabilities</key>
    <array>
      <string>arm64</string>
      <string>metal</string>
      <string>arkit</string>
    </array>
`
I tried changing change arm64 in UIRequiredDeviceCapabilities in info.plist to armv7 but I still get the error notification by apple when I upload tge app to the store.

Are you aware whether there is a solution for those who built back in 2018 with arfoundation or we need to delete the app from the store to update it?

Thanks for your guidance !

**Comment by tdmowrer** [comment]
Hi. I don't work at Unity anymore but according to the change log, you should be able to use 2.1.9+. See https://docs.unity3d.com/Packages/com.unity.xr.arkit@2.1/changelog/CHANGELOG.html?q=32%20bit

**Comment by sergiosolorzano** [comment]
Thanks a lot @tdmowrer, we'll try it out ! I wish you all the very best in your next endeavour, it's a shame for all us as you've been super helpful and fun to interact everytime over the past few years ! Hope to cross paths again, cheers !

**Comment by tdmowrer** [comment]
Thanks! That's really great to hear; thanks for the kind words and well wishes.
