### ISSUE TITLE
Support for Exposure/ISO lock

### ISSUE THREAD

**Issue by DiveshNaidoo** [Unity-Technologies/arfoundation-samples#324]
Hi, I'm not sure if this functionality has already been implemented but I am trying to find a way to access and set the ISO value on my devices camera when using ARFoundation. Is this possible?

**Comment by tdmowrer** [comment]
In ARFoundation, you can get the [exposure duration and offset](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs.html), but you cannot set them. Support for this is currently limited to iOS.

**Comment by DiveshNaidoo** [comment]
Thank you for your response, how would you go about setting the value with iOS? I can't seem to find any documentation regarding this.

**Comment by tdmowrer** [comment]
I don't believe you can set these values when ARKit is running.

**Comment by sam598** [comment]
@DiveshNaidoo Because ARKit is doing 6dof tracking with a single RGB camera, it needs full control of the camera's auto exposure in order to find good features to track. The same is true with ARCore, and Project Tango before it.

In theory it is possible that future devices with multiple cameras could use one camera for tracking and allow exposure control for another camera that is being augmented. But it is unlikely that a company like Apple or Google could be persuaded to support a niche use case.

**Comment by Macoron** [comment]
Sorry for necro, but this isn't longer the case. ARKit has provided `configurableCaptureDeviceForPrimaryCamera` which allow you to change exposure values and other parameters in ARKit session. [More information here.](https://developer.apple.com/documentation/arkit/arconfiguration/3930045-configurablecapturedeviceforprim?changes=__6)

Any plans to add this to AR Foundation?
