### ISSUE TITLE
Can't install AR Foundation version 3.0 in Unity 2019.3.0b6

### ISSUE THREAD

**Issue by ufktvfk** [Unity-Technologies/arfoundation-samples#326]
Hi,
I am currently using Unity 2019.3.0b6 and I need to install the latest version of  AR Foundation to my project.
![ARFoundationV2](https://user-images.githubusercontent.com/23186662/66731505-662ce480-ee60-11e9-807c-a017588fd3cc.jpg)

BUT I cannot see version 3.0 in my project. Is it because I use a beta version? 

I am a content creator and that's why I use Unity 2019.3 beta so I really need to install the latest version.
If you can help me with this issue, I would be glad. Thanks.

**Comment by tdmowrer** [comment]
Since this issue is closed, I assume you found the answer, but for future readers, you need to enable preview packages from the Package Manager > Advanced > Show Preview Packages:
![Screen Shot 2019-10-14 at 11 49 35 AM](https://user-images.githubusercontent.com/4934281/66775407-bdd74a00-ee78-11e9-9a15-6d54f5225fc5.png)

**Comment by ufktvfk** [comment]
Yes. Sorry about that. Hope it will help future readers.
