### ISSUE TITLE
Methods missing from ARSubSystems on install

### ISSUE THREAD

**Issue by JhonTC** [Unity-Technologies/arfoundation-samples#329]
Just Installed AR Foundation, ARCore XR Plugin & ARKit XR Plugin and got all these errors!
Using Unity version: 2019.3.0a8
![Screenshot_19](https://user-images.githubusercontent.com/47017277/66831966-ca2ed600-ef50-11e9-80ba-0d90f936d024.jpg)

**Comment by JhonTC** [comment]
Just realised I have submitted this in the wrong place! Sorry, still any help would be lovely XD

**Comment by DavidMohrhardt** [comment]
What version ARSubsystems are you using?  If it's 2.2.x then you should upgrade to 3.0.0-preview.  If you are tied to a verified package then you should use 2.1.1.

The context is that there was a bug with scenes that got fixed via changing the way the destruction of subsystems is handled.  This change exists in 2.1.1 and 3.0.0 but 2.2.x does not have the change (since it evolved into 3.0.0)

**Comment by DavidMohrhardt** [comment]
Actually upon further inspection I see the issue now.  You are likely on 3.0.0-preview for ARFoundation but the version of Unity you are using does not contain the fix.  You will need to roll back to an earlier preview of ARFoundation or update Unity to at least 2019.3.0b6.

**Comment by tdmowrer** [comment]
This should be resolved now. ARFoundation 3.1.3 is verified for 2020.1 and is compatible with 2019.3.
