### ISSUE TITLE
Losing face tracking in the landscape mode

### ISSUE THREAD

**Issue by hyeonseung-yu** [Unity-Technologies/arfoundation-samples#364]
Hi, I highly appreciate sharing great examples. 

I'm testing FacePose and FaceMesh examples on a Google Pixel 3a. The example programs work totally fine in the portrait mode, but I found that they easily lose face tracking in the landscape mode depending on the orientation of the phone. For example, if I hold up the phone so that the phone screen is perpendicular to the ground, the face tracking works fine. But if I put the phone on the desk, which means that the phone screen is parallel to the ground, and look from the above, then those examples cannot detect my face anymore. I tested with many different lighting conditions and backgrounds, and I'm pretty sure that the phone orientation and the landscape mode are the main factors. Is there any particular configuration that can solve this issue?

**Comment by LexRillo** [comment]
I have experienced the same behaviour under the same conditions. I believe this happens when the face is looking at the camera with the phone in "portrait position" and not when the scene is in portrait or landscape mode. If you hold your phone upright and it starts tracking your face from that position, you can move your face and the tracking will follow the face accordingly. But if no face is track and one appears rotated (by 90 degrees) then it will not be tracked. [And yes, this involved a lot of weird contortions to test]. This also happens regardless of the distance to the camera. Hopefully this gives a more detail to the problem and it can be fixed soon.

**Comment by tdmowrer** [comment]
This is an artifact of the way ARCore performs face tracking. It uses a machine learning model that relies on (more or less) upright faces.

I'm curious: what use case requires you to perform face tracking with your device on a horizontal surface rather than being held upright?
