### ISSUE TITLE
Memory usage goes up by about 100 - 150 MB on each AR scene loading until app crashes, when repeated scene reloading 

### ISSUE THREAD

**Issue by boboEmily** [Unity-Technologies/arfoundation-samples#378]
AR foundation preview.1 - 3.1.0

Very easy to reproduce this issue.

Add a button to any AR scene to SceneManager.LoadScene itself. When scene launches, repeated press that button to reload itself. Memory usage will increase by 100 - 150 mb every time the new scene loaded, until it goes above around 2 GB and the app will crash because of memory issue.

It doesn't matter whether it's loading itself or another scene. I tried to add two buttons to alternatively load two AR scenes, the issue is the same.

**Comment by FantasyTianyu** [comment]
Same issue. Many people found this bug and post it to unity forum,but it have not be fiexd for a long time,this bug fixed in ARFoundation 2.0,when i use ARFoundation 2.0 with unity 2018,there is no memory leak,but appeared in ARFoundation 3.x version

**Comment by tdmowrer** [comment]
We've identified a bug in the ARKit XR Plugin which will be fixed. Can you confirm this is iOS only?

**Comment by horatiu665** [comment]
I am also getting a heavy memory leak related to AR on android. However I am getting it constantly, unrelated to scene loads. Something with Texture memory (according to profiler). In my case I tried arfoundation 3.x as well as 4.x which is a few days old. Only discovered reason of crash after profiling from the build, connected phone via usb.

Trying to figure out if it's something to do with the camera blit things, render texture.... materials being created and not sharedMaterials...??? it's a guessing game, and it's really hard since I have ~30 seconds before a crash, and I can only do it from a build.

This could have maybe been avoided by having an instant preview of AR running from the editor... we desperately need that guys! not to mention build times are sooo long with IL2CPP.

I'll try to update here as I debug further.
