### ISSUE TITLE
Checking for Device Support is invalid

### ISSUE THREAD

**Issue by Leiong** [Unity-Technologies/arfoundation-samples#388]
Unity：Unity2018.4.14f1
ARFoundation:1.50-preview.7
ARCoreXRPlugin:2.20-Preview.6
Device:  MI 5

The check code is as follows：`
public class MyComponent {
    IEnumerator Start() {
        if (ARSession.state == ARSessionState.None ||ARSession.stateARSessionState.CheckingAvailability)
        {
            yield return ARSession.CheckAvailability();
        }

        if (ARSession.state == ARSessionState.Unsupported)
        {            
             Debug.Log("Unsupported");
            // Start some fallback experience for unsupported devices
        }
        else
        {
             Debug.Log("Supported");
            // Start the AR session
        }
    }
}
`

**Comment by Leiong** [comment]
![0200102101955](https://user-images.githubusercontent.com/41097890/71649422-a73ee180-2d49-11ea-9b0c-c5432d77fc55.png)
MI5 phones do not support AR, but they cannot be checked out correctly. This is just an example. I also checked with other equipment. the problem still exists.

**Comment by tdmowrer** [comment]
This is the expected behavior when ARCore is "required" (the default). This is because you would not normally be able to install an ARCore required app on an unsupported device, so ARCore assumes if you are running an app that requires ARCore, then the device is supported. By building and deploying from Unity, you are "side loading" your apk and circumventing this restriction.

See also the [ARCore docs](https://developers.google.com/ar/reference/c/group/arcoreapk#arcoreapk_checkavailability) on this. In the ARCore XR Plugin package, you can [specify that ARCore is "optional"](https://docs.unity3d.com/Packages/com.unity.xr.arcore@3.0/manual/index.html#build-settings) to support a fallback experience on unsupported devices.
