### ISSUE TITLE
Android. Face Tracking is slow [Bug]

### ISSUE THREAD

**Issue by andrewio** [Unity-Technologies/arfoundation-samples#432]
Demo called "Face Mesh" has about 0.5 second latency on camera background feed. 
If I run other demos which use rear camera then there is no latency. 

I also tested default camera app on my phone. There is no latency for Face Camera.

Environment:
- Samsung Galaxy A71. 
- Android 10.
- AR Foundation. 3.0.1.
- Unity 2019.3.5.f

P.S. iPhone XS Max has not any delays on this demo and seems that FPS is bigger here, it is very smooth unlike Android.

**Comment by tdmowrer** [comment]
ARCore delays the CPU image frames to run [machine learning models](https://www.google.com/url?q=https://ai.googleblog.com/2019/03/real-time-ar-self-expression-with.html&sa=D&source=hangouts&ust=1585073144718000&usg=AFQjCNG3-Rvq-S9b8tSAoXyRY7jut3jkcw) when face tracking is enabled. The exact amount varies (e.g., according to CPU resources), but ARFoundation always displays the latest camera image provided by ARCore.

To eliminate ARFoundation as a factor, I compared the "Face Mesh" ARFoundation sample with the "AugmentedFaces" sample in [Google's ARCore SDK for Unity plugin](https://github.com/google-ar/arcore-unity-sdk) and got the same results. The delay is significant on a Pixel 3a.

What you have described is the expected behavior.

**Comment by tdmowrer** [comment]
Also, logcat output from ARCore will tell you by how many frames the camera image is delayed. For example:
```
I native  : session.cc:2571 Update Frame Delay to 6 frames.
```

**Comment by andrewio** [comment]
> Also, logcat output from ARCore will tell you by how many frames the camera image is delayed. For example:
> 
> ```
> I native  : session.cc:2571 Update Frame Delay to 6 frames.
> ```

Got it. Thx. So there is no way to make delay smaller? 
I tried Instagram App & Masks here on same Device. Delay is smaller, almost 0.
Instagram doesn't use ARCore or Unity Environment makes delay?

And Please tell me, Tim, What about Frame Rate? 
Seem that on Android target frame rate is low by default unlike iOS.

What is your Recommendation of setting target frame rate in case of AR Foundation on Android?

**Comment by tdmowrer** [comment]
> So there is no way to make delay smaller?

No, this is up to ARCore.

> Instagram doesn't use ARCore or Unity Environment makes delay?

Instagram has their own face tracking technology; they do not use ARCore as far as I know.

> What about Frame Rate?
> Seem that on Android target frame rate is low by default unlike iOS.

Most Android devices only support 30 fps while iOS devices support 60 fps. While some newer Android devices do support 60 fps (this [list of supported devices](https://developers.google.com/ar/discover/supported-devices) tells you which ones), I don't think any of them support 60 fps in the front-facing camera mode.

> What is your Recommendation of setting target frame rate in case of AR Foundation on Android?

By default, the framerate is set automatically and is generally the best available on the device. There are ways to [query for available frame rates](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@3.0/api/UnityEngine.XR.ARSubsystems.XRCameraSubsystem.html#UnityEngine_XR_ARSubsystems_XRCameraSubsystem_GetConfigurations_Allocator_) and [disable the automatic management of the Unity framerate](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARSession.html?q=match%20frame%20rate#UnityEngine_XR_ARFoundation_ARSession_matchFrameRate).
