### ISSUE TITLE
"TryGetLastestImage" return an image with larger view than the image on ar camera background

### ISSUE THREAD

**Issue by BoneFlat** [Unity-Technologies/arfoundation-samples#476]
Hi Unity AR Team, I'm trying to detect hand in single frame..
I'm getting image from "TryGetLastestImage" but it has larger view than the image on ar camera background and skewed my results. 
How can i get an image has the same view with the one on camera background?

**Comment by tdmowrer** [comment]
What do you mean by "larger view"?

**Comment by BoneFlat** [comment]
lin the image below, the small image at top-left is the result of "TryGetLastestImage", i can see more thing in it 
![image](https://user-images.githubusercontent.com/62471272/81945401-447b2200-9628-11ea-8bf0-a1cd26f48e5b.png)

**Comment by tdmowrer** [comment]
One is the GPU image and the other is the CPU image provided by ARCore or ARKit. They aren't necessarily the same. We also surface the camera intrinsics, which are needed for the type of computer vision application you're doing.

**Comment by tdmowrer** [comment]
You can, but it takes time because it must be transferred from the GPU. See [AsyncGPUReadback](https://docs.unity3d.com/ScriptReference/Rendering.AsyncGPUReadback.html).

Probably the reason you see a difference in this case is because the image may be stretched slightly to fill the screen (this [display matrix](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs.html#UnityEngine_XR_ARFoundation_ARCameraFrameEventArgs_displayMatrix)) is applied in the ARKit shader. You can apply a similar mapping to the image you get from `TryGetLastestImage` if you need to exactly match what you see on screen.

**Comment by BoneFlat** [comment]
I have solve my problem with a basic mapping .Thanks for quick reply and support, Tim.
I'm very appreciate!

**Comment by D3m0n92** [comment]
> I have solve my problem with a basic mapping .Thanks for quick reply and support, Tim.
> I'm very appreciate!

Can I ask you how exactly you did it? I have the same problem.

**Comment by arvrschool** [comment]
Can I ask you how exactly you did it? I have the same problem too.
