### ISSUE TITLE
Getting error message using front camera.

### ISSUE THREAD

**Issue by noppefoxwolf** [Unity-Technologies/arfoundation-samples#484]
```
No active UnityEngine.XR.XRInputSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.

UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogWarningFormat(String, Object[])
UnityEngine.XR.ARFoundation.ARInputManager:GetActiveSubsystemInstance()
UnityEngine.XR.ARFoundation.ARInputManager:OnEnable()
```

**Comment by tdmowrer** [comment]
Well, have you ensured "that a valid loader configuration exists in the XR project settings"? ARFoundation now uses XR Management to decide which provider to use (because there could be multiple options). See https://docs.unity3d.com/Manual/configuring-project-for-xr.html for details. Basically just tick the "ARCore" and/or "ARKit" boxes in Project Settings > XR Plugin Management.

**Comment by noppefoxwolf** [comment]
@tdmowrer Thank you very much. I resolved issue.
