### ISSUE TITLE
Can't see light estimation information displayed on app  

### ISSUE THREAD

**Issue by s-hurli** [Unity-Technologies/arfoundation-samples#488]
using Pixel 3a, Android 10 - built the Unity project for Android and downloaded it for testing - the app only displays 3 buttons that do not work (Recv, Send, Has Collaboration Data), session id, session state, tracking state, a message about the log console, a message about collaborative sessions being unavailable, and a button to remove local reference points. No light estimation information is displayed at all - nor is it noted to be unavailable. What could the issue be?

**Comment by tdmowrer** [comment]
It sounds like you're running the [collaborative session sample](https://github.com/Unity-Technologies/arfoundation-samples#arcollaborationdata), rather than any sample to do with light estimation. Collaborative sessions are only supported by iOS 13+, which is why you see "a message about collaborative sessions being unavailable" on Android.

**Comment by s-hurli** [comment]
I cloned the whole project & built it for Android. How do I run the light estimation sample?

**Comment by s-hurli** [comment]
Thanks for the quick response by the way!

**Comment by tdmowrer** [comment]
In the build menu, you can select which scenes are included in the build. If none are selected (the current state of this repo), then it will launch the scene you currently have open.
