### ISSUE TITLE
Building Android with Gradle Export project causes manifest error and camera failure

### ISSUE THREAD

**Issue by beachgrub** [Unity-Technologies/arfoundation-samples#50]
Using Unity 2018.1.7f1

If we build Android using gradle export project, the project with throw an error that it can't find the manifest path.  Like this:

DirectoryNotFoundException: Could not find a part of the path "D:\Projects\PROJECTNAME\client\UnityProject\Builds\GeneratedApkTemp\src\main\AndroidManifest.xml".
System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileStream.cs:292)
System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share)
(wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
System.Xml.XmlUrlResolver.GetEntity (System.Uri absoluteUri, System.String role, System.Type ofObjectToReturn)
Mono.Xml2.XmlTextReader.GetStreamFromUrl (System.String url, System.String& absoluteUriString)
Mono.Xml2.XmlTextReader..ctor (System.String url, System.Xml.XmlNameTable nt)
System.Xml.XmlTextReader..ctor (System.String url, System.Xml.XmlNameTable nt)
System.Xml.XmlDocument.Load (System.String filename)
UnityEditor.XR.ARCore.ARCoreManifest.OnPostGenerateGradleAndroidProject (System.String path) (at C:/Users/jlander/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.xr.arcore@1.0.0-preview.17/Editor/ARCoreBuildProcessor.cs:193)

The problem is the actual path in the built project has the project name in there
"client\UnityProject\Builds\GeneratedApkTemp\PROJECTNAME\src\main\AndroidManifest.xml"

Manually adding the project name into line 202 of ARCoreBuildProcessor fixes the issue:
string manifestPath = path + "/PROJECTNAME" + k_AndroidManifestPath;

I am not sure how to do this correctly.

**Comment by UgurIster** [comment]
yeah, i stumbled over the same thing today.
You're right, the ARCoreBuildProcessor.cs in the package should be changed so that when one had set it in the build settings to deploy an apk line 181 should still be
string manifestPath = path + k_AndroidManifestPath;
and when set to deploy an Androidproject it should instead be
string manifestPath = path + "/projectName" + k_AndroidManifestPath;
like you said.

**Comment by tdmowrer** [comment]
This is an [issue](https://issuetracker.unity3d.com/issues/android-ipostgenerategradleandroidproject-dot-onpostgenerategradleandroidproject-returns-incorrect-path-when-exporting-a-project) in the `IPostGenerateGradleAndroidProject` (it provides an incorrect path when exporting), which is fixed in 2018.3. I'll investigate whether we can add a workaround for earlier versions.

**Comment by UgurIster** [comment]
ok, nice, thanks for the info and looking into it =)
We'll likely switch soon to 2018.3 for the project anyway (it is a bit more involved since for this project we embed unity inside a native app so it takes more work to ensure all still works well with newer versions as they sometimes affect the integration),
but good if the fix can be back ported to some older versions, too.
