### ISSUE TITLE
[AR Face Tracking] iOS 13.5 opens back camera for the moment, then front camera

### ISSUE THREAD

**Issue by andrewio** [Unity-Technologies/arfoundation-samples#506]
So at scene start iOS 13.5 opens back camera for the moment (0.2 sec), then front camera.

Is it normal behavior?
How to avoid back camera opening?

**Comment by tdmowrer** [comment]
Are you running one of the sample scenes from this repo? If so, which one? If not, can you post a code snippet or describe your scene setup?

**Comment by pulterao** [comment]
I am having this issue as well. Building the FaceMesh sample opens the back camera instead of the front camera.

This is happening only on devices **without** true depth camera (Iphone se, Ipad air...), IphoneX works as expected.

iOS version: 13.4.1
Unity version: 2019.4.0f1
ARfoundation Samples: 3.1

Package versions:
ARFoundation: 3.0.1
AR Subsystems: 3.0.0
ARkit Facetracking: 3.0.1
ARkit XR Plugin: 3.0.1

**Comment by tdmowrer** [comment]
@pulterao That is the expected behavior. On iOS, you can only enable the front facing camera on devices with a TrueDepth camera.
