### ISSUE TITLE
Anchor Raycast Pose

### ISSUE THREAD

**Issue by meihkkkkkkk** [Unity-Technologies/arfoundation-samples#558]
Hi, I have recently asked some questions about scanning QR to display anchors.
In the Anchors scene of sample project, I believe this code is to spawn anchors:

`            
            if (Input.touchCount == 0)
                return;

            var touch = Input.GetTouch(0);
            if (touch.phase != TouchPhase.Began)
                return;
            if (m_RaycastManager.Raycast(touch.position, s_Hits, TrackableType.FeaturePoint))
            {
                var hitPose = s_Hits[0].pose;
                var anchor = m_AnchorManager.AddAnchor(hitPose);
                if (anchor == null)
                {
                    Logger.Log("Error creating anchor");
                }
                else
                {
                    m_Anchors.Add(anchor);
                }`
Also, I have add a line to display the s_Hits[0].pose rotation (a quaternion with w,x,y,z). Most times, the value of x and z is 0, so that the front side of anchor is faced to the phone camera.

The problem is, I'm replacing "touch.position" in the code above with a Vector2, which is position of scanned QR code. While the anchors spawn in correct position, it's rotation is not stable (w,x,y,z are keep changing, and x,z are not 0). I have tried to modify s_Hits[0].pose.rotation, but seems like it cannot be modified (not variable).

So what is the s_Hits[0], where's its value come from? And can you suggest me some solutions for my problem? 
Thank you

**Comment by tdmowrer** [comment]
> it's rotation is not stable (w,x,y,z are keep changing, and x,z are not 0)

You are raycasting against feature points, which can include an orientation (an estimate of the surface the feature point is on), so they aren't always facing in a consistent direction.

> I have tried to modify s_Hits[0].pose.rotation, but seems like it cannot be modified (not variable).

This is because `pose` is a `struct` and `struct`s are always copied by value, so `s_Hits[0].pose.rotation` gives you a copy of the pose's rotation. The error you are probably seeing is the compiler telling you that ```s_Hits[0].pose.rotation = some_other_rotation``` won't work, because you can't assign to a temporary copy (and if you could, it wouldn't do anything useful).

As I understand your use case, you should just make a copy of the rotation, modify it, and construct a new `Pose` from that. So

```csharp
var hitPose = s_Hits[0].pose;
var rotation = hitPose.rotation;
// modify rotation to your liking
m_AnchorManager.AddAnchor(new Pose(hitPose.position, rotation));
```

**Comment by meihkkkkkkk** [comment]
Hi @tdmowrer , it works perfectly. Thank you
