### ISSUE TITLE
Exact prefab spawning location (Image Tracking)

### ISSUE THREAD

**Issue by livpasdiora** [Unity-Technologies/arfoundation-samples#565]
Hello everyone! I'm working on an AR app for the construction industry. I'm trying to define the exact location where my prefab appears when the application recognizes the QRcode. How can I do this? I need to spawn real size prefabs (1: 1 scale) and I can't figure out how to position the QR code correctly inside the ImageInfoPrefab. Thank you in advance!

![ImageTrackingIssue](https://user-images.githubusercontent.com/61844578/88832850-c8fd2b80-d1a7-11ea-9f99-2fca49f49cc2.png)

**Comment by DavidMohrhardt** [comment]
Just so I am clear on the use case.  You want to spawn a 1:1 size model when the device detects an image in the environment at the proper real world position and orientation, correct?

The simplest way would be to have that QR code on the prefab be centered at the "prefab space" origin `<X: 0, Y: 0, Z: 0>` (with the proper so that when the prefab get's instantiated when it is detected it should automatically be at the proper placement.  One way you could do this is to set the rest of the model as a child of the QR code in your prefab then set the QR code's default transform to the origin.

**Comment by livpasdiora** [comment]
Yes, exactly! I'll try it, thanks for your help :)
