### ISSUE TITLE
[Bug] Image Tracking using iOS: Prefab Instance Position is wrong/floating

### ISSUE THREAD

**Issue by marwie** [Unity-Technologies/arfoundation-samples#568]
**Unity bug report case number**
1266976

**Describe the bug**
Tracked Images position (instantiated prefabs) do not match real world location

**To Reproduce**
1) open image tracking sample
2) add AR Plane Manager and use e.g. the occlusion plane prefab as a plane prefab
3) add "PlaceMultipleObjects" script and use e.g. the AR Cube prefab as a object prefab
4) build to iOS
5) use e.g. the QR code image (printed) to be tracked
6) place the image e.g. on a plane surface like the floor or a table
7) run the app and track the image. it appears visually at the exact same position where the real world image is on the screen - this is good and looks correct
8) place some cubes by tapping on the tracked plane around and onto the tracked image
9) note: the cubes are ALWAYS below the tracked plane (in another project of mine they are always on top - not sure why it is inverted in the samples project)
10) tilt your device slightly / view the tracked image from a more skewed perspective - once tracking gets lost or is limited you can notice how it floats way above (or below) the actual image on the surface - if tracking would have been correct I would expect it to be more or less still at the same position on the surface, if it didnt change in real life

**Expected behavior**
Placed cubes should be either on top or intersecting the tracked plane - the instantiated tracked image prefab should virtually be almost at the same surface position as my tracked plane

**Actual behavior**
see steps to reproduce description

**Smartphone (please complete the following information):**
 - Commit: aab62c0d74d18375e50d81ae6b4374bd992195d3  Upgrading to Unity 2019.4.5f1.
 - Device: iPhone SE
 - OS: iOS 13.5.1
 - Unity version 2019.4.4f1
 - ARFoundation version:
```
    "com.unity.xr.arfoundation": "4.1.0-preview.5",
    "com.unity.xr.arkit": "4.1.0-preview.5",
```

Example when image is tracked with placed cubes (noite cubes get occluded by the tracked image which actually is pretty much at the same level as the floor)
![IMG_0098](https://user-images.githubusercontent.com/5083203/88918728-3e313500-d26a-11ea-83c2-b6efbc404ea5.PNG)

but when tilting slightly and tracking gets lost:
![IMG_0099](https://user-images.githubusercontent.com/5083203/88918802-5e60f400-d26a-11ea-8893-98e57b310496.PNG)

**Comment by marwie** [comment]
Here is a video https://photos.app.goo.gl/JuGGPfxDLjp1RzZGA

**Comment by SHELLEYJ32** [comment]
Hi, after doing some tests with the project you uploaded, I was able to reproduce the issue but not 100% of times. I've attached some pictures of the successful cases, where the cube is on top of the QRCode. 

Two points to help you debug: 
1)The imageInfoPrefab spawned in the Image Tracking sample could take some time to adjust to correct positions. You should move your phone slightly and wait a few seconds to see if the QRCode position updates. 
2)Since the plane detection also can and will adjust their positions over time. Use the `AR Plane Debug Visualizer` as the prefab and try to debug from there.

![IMG_6129](https://user-images.githubusercontent.com/44713951/89911217-28ebcd00-dbbf-11ea-8e48-0b7044a158bd.png)

![IMG_6130](https://user-images.githubusercontent.com/44713951/89911175-1f626500-dbbf-11ea-86d1-59103d15bbba.png)

**Comment by marwie** [comment]
Hello, this is still an issue. We are shipping an app with this feature. Image tracking is broken in almost all cases and thats not a solution. Is it not considered a bug if a feature is only working like 70% of the time?The feature is not useable for us if tracking is unreliable like this, would you please forward the issue to the developers, otherwise it remains in a half broken state and thats frustating and it is exactly what drives me away from Unity.its not my job to debug halfway broken features from Unity, I can not fix it on my side, only workaround and ive been testing enough to figure out that the issue is not on our side and report this as a bug.Am 11.08.2020 16:50 schrieb Shan Jiang <notifications@github.com>:
Hi, after doing some tests with the project you uploaded, I was able to reproduce the issue but not 100% of times. I've attached some pictures of the successful cases, where the cube is on top of the QRCode.
Two points to help you debug:
1)The imageInfoPrefab spawned in the Image Tracking sample could take some time to adjust to correct positions. You should move your phone slightly and wait a few seconds to see if the QRCode position updates.
2)Since the plane detection also can and will adjust their positions over time. Use the AR Plane Debug Visualizer as the prefab and try to debug from there.

**Comment by marwie** [comment]
This is still relevant to us

**Comment by tdmowrer** [comment]
The issue is that you need to accurately specify the size of the physical image. To exaggerate the issue, you can tell ARFoundation the QR code is 10 x 10 meters. When it is detected, it will be placed very far away (because if you assume it is 10 meters wide, and you see an image that has a small _apparent_ size, then you must just be viewing it from a very far distance).

To measure this precisely, you can attach the following script to your image prefab:
```csharp
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.ARSubsystems;

[RequireComponent(typeof(ARTrackedImage))]
public class DistanceToPlane : MonoBehaviour
{
    ARRaycastManager m_RaycastManager;

    ARTrackedImage m_TrackedImage;

    void Start()
    {
        m_RaycastManager = FindObjectOfType<ARRaycastManager>();
        m_TrackedImage = GetComponent<ARTrackedImage>();
    }

    void Update()
    {
        var ray = new Ray(transform.position + transform.up, -transform.up);

        if (m_RaycastManager.Raycast(ray, m_Hits, TrackableType.PlaneWithinPolygon))
        {
            var hit = m_Hits[0];
            Debug.Log($"{m_TrackedImage.referenceImage.name} distance to plane => {Vector3.Distance(hit.pose.position, transform.position)}");
        }
    }

    List<ARRaycastHit> m_Hits = new List<ARRaycastHit>();
}
```

In my tests, it was initially several centimeters off, but when I measured the dimensions of the printed QR code exactly, the resulting difference between the image and the plane was about 1-2 millimeters. Note that the QR code image has a white border, so if you print it on white paper it is difficult to measure the exact printed dimensions. I added a black border to make it easier to measure the dimensions when printed on a white background:

![QRCode](https://user-images.githubusercontent.com/4934281/93405134-0cd3ef00-f841-11ea-860f-6a866871b07f.png)

**Comment by marwie** [comment]
Hello Tim, thanks for clarifying! That makes sense. 

Maybe the documentation could be more specific about it? It just says it could improve image detection.
It also says I should check the providers documentation but there is e.g. no further info about arkits requirements https://docs.unity3d.com/Packages/com.unity.xr.arkit@latest

**Comment by tdmowrer** [comment]
> Maybe the documentation could be more specific about it?

Yep, for sure. I don't think we ever noticed this behavior because when viewing the image overlay, it will always "appear" to be in the correct position. The issue is only apparent when you compare its position relative to other things, like the plane on which it rests.

**Comment by marwie** [comment]
Yeah same here, that's why I forgot about image size as it always looked correct. So thanks again, I'll close this then

**Comment by marcusx2** [comment]
@tdmowrer This issue happens when I'm trying to use Vuforia + ARFoundation. I followed [this tutorial](https://library.vuforia.com/articles/Solution/ar-foundation.html) but the content's position is wrong. It looks fine on Android though.

**Comment by tdmowrer** [comment]
> @tdmowrer This issue happens when I'm trying to use Vuforia + ARFoundation. I followed [this tutorial](https://library.vuforia.com/articles/Solution/ar-foundation.html) but the content's position is wrong. It looks fine on Android though. What can I do to fix it? I'm using Vuforia for the image tracking, but using ARFoundation's camera like the tutorial explains.

Your question seems unrelated to this closed issue. While this forum isn't for questions about Vuforia, if you have a specific question about how the AR Foundation camera works, please open a new issue.

Also, a couple of things to keep in mind:
- I no longer work at Unity, so I won't comment on AR Foundation specifically. 
- Your question is about Vuforia, so this probably isn't the right forum for your question.
