### ISSUE TITLE
Stabilize the spawned model during tracking

### ISSUE THREAD

**Issue by sandrobl** [Unity-Technologies/arfoundation-samples#577]
Hello everyone,

I managed to spawn a model at a sight of a specific QR-Code but sadly the model jitters a lot. 

Here a link to video showing the jittering in action (https://youtu.be/yFfj_Mhb91M) 

The AR Foundation project uses the newest version of both AR Foundation(3.1.3) and the ARCore PlugIn(3.1.5). It runs on a Nokia 7.2 Android-Version 10.

Is there a way to optimize this?

Much thanks.

**Comment by tdmowrer** [comment]
Based on the video, it looks like you are trying to drive the position of your content according to the camera's transform; is that correct?

In that case, you should update its position in an [`onBeforeRender`](https://docs.unity3d.com/ScriptReference/Application-onBeforeRender.html) callback, not in `Update`. This is because the camera's transform is not updated until just before rendering, so the pose you get in `Update` is a frame behind. On Android in particular, being a frame off can produce pretty jittery results like what you've captured in the video.

We do something similar in one of our samples -- see this [code snippet](https://github.com/Unity-Technologies/arfoundation-samples/blob/c384d0600108688db9a10870141fda3243fdca3b/Assets/Scenes/LightEstimation/FacingDirectionManager.cs#L63-L70).

**Comment by sandrobl** [comment]
Yes, the plan is to display the model where the QR Code is located. The thing is I use the Standard XR Components "AR Session", "AR Session Origin" and "AR Tracked Image Manager". So I didn't wrote any additional code. 

One thing, the model that is beeing used is rather big. Is there a limitation on how big this model can be? Because, I tried a simple "sphere" as a replasement and the jittering was not that visible anymore.

**Comment by tdmowrer** [comment]
> Yes, the plan is to display the model where the QR Code is located. 
> Is there a limitation on how big this model can be? Because, I tried a simple "sphere" as a replasement and the jittering was not that visible anymore.

It sounds like you might be seeing a sort of "lever arm" effect if the pivot of your large model is meant to be driven by the QR code location (which will move very slightly as ARCore updates it). Could that be the case here?
