### ISSUE TITLE
[Bug] ar foundation -2019.4 LTS version + ar foundation + ar kit rendering black camera in iPhone

### ISSUE THREAD

**Issue by ShaziyaXR** [Unity-Technologies/arfoundation-samples#587]
**Unity bug report case number**
Please log a bug at https://unity3d.com/unity/qa/bug-reporting and post the case number here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13]
 - Unity version
 - ARFoundation version

**Comment by tdmowrer** [comment]
@ShaziyaXR This seems like an issue opened by mistake. I'll close it, but please reopen this issue with more detail if you would like help with an issue.

**Comment by fsal-code** [comment]
Having the same issue here and it's incredibly frustrating. It happened after updating from ARKit 3.1.0 preview 8 to 4.0.2 (same for ARFoundation). I'm using unity 2019.3. Deleting xcode project and rebuilding doesn't work. Deleting library folder and reimporting project doesn't work. ArFoundation sample scene gives the same black screen. No errors in Xcode. just black screen.

**Comment by tdmowrer** [comment]
@fsal-code  Sorry, but there is not information here for us to act on. Please create a separate issue for your specific problem. It would be helpful if [log a bug](https://github.com/Unity-Technologies/arfoundation-samples/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBug%5D) and attach your project so that we can try to reproduce the issue.
