### ISSUE TITLE
GPU/CPU Camera image from compute shader

### ISSUE THREAD

**Issue by amir989** [Unity-Technologies/arfoundation-samples#590]
So, I need to use the phone camera image in my shader graph. I cant have the phone camera image as a texture for my shader graph from GPU. I have to take slower approach and get the camera image from CPU. I thought a better approach would be filling a RenderTexture with camera image by a compute shader. So it would be faster than the CPU version and I have access to the camera image from both C# code and shader graph and save 8-12 milsec. I did my best to convert your GPU shader to a compute shader but I failed. If you guys see the same advantage Could you do the compute shader? or at least create a shader graph node, where we can have access to the GPU version of the camera image? 

Thanks a bunch

**Comment by DavidMohrhardt** [comment]
You can perform a "blit" without ever having to copy the CPU texture.  This is recommended because there is a possibility that the underlying background texture will not last beyond the frame boundary (in single-threaded rendering when using ARCore for example).  We give the following recommendation in our [documentation](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/index.html#copying-the-camera-texture-to-a-render-texture-when-accessing-the-camera-image-on-the-gpu).

> Camera Textures are likely external Textures and might not last beyond a frame boundary. It can be useful to copy the Camera image to a Render Texture to persist it or process it further. The following code sets up a command buffer that will clear the render target and then perform a GPU copy or "blit" to a Render Texture of your choice immediately:

```csharp
var commandBuffer = new CommandBuffer();
commandBuffer.name = "AR Camera Background Blit Pass";
var texture = !m_ArCameraBackground.material.HasProperty("_MainTex") ? null : m_ArCameraBackground.material.GetTexture("_MainTex");
Graphics.SetRenderTarget(renderTexture.colorBuffer, renderTexture.depthBuffer);
commandBuffer.ClearRenderTarget(true, false, Color.clear);
commandBuffer.Blit(texture, BuiltinRenderTextureType.CurrentActive, m_ArCameraBackground.material);
Graphics.ExecuteCommandBuffer(commandBuffer);
```

> Note: `Graphics.SetRenderTarget` will overwrite the current render target after executing the command buffer.

Keep the `Note` section above in mind.  You may need to reset the render target back to its original target.

Additionally, you can also grab the textures themselves from the `ARCameraManager.frameReceived` event by accessing the ['textures' proprety in the 'ARCameraFrameEventArgs' struct](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/api/UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs.html#UnityEngine_XR_ARFoundation_ARCameraFrameEventArgs_textures)

```csharp
// Somewhere during initialization
m_ArCameraManager.frameReceived += OnFrameReceived;

// ...

public void OnFrameReceived(ARCameraFrameEventArgs evtArgs)
{
    // get a list of "external" (GPU only, may not last beyond frame boundary) textures for the current frame
    var cameraTexture2Ds = evtArgs.textures;
    // do something with the textures...
}
```
Though these textures may not last beyond the frame boundary like above so performing some form of copy might be required depending on the use of these textures.

Hopefully this provides you an avenue forward!

**Comment by amir989** [comment]
Thanks for respond David. 

I have tried the first method a while ago on an iPhone Xs. I needed to save a picture from selfie camera and the problem with the method was that some of the pixels in the saved picture on memory were missed. Like some of the pixels in the pictures had wrong pixel color. Im not sure if I did reset the render target that time. But I can try that sometimes soon!! 

The second method always give me a null List! 

I'm a bit busy with a deadline now. But ill try them again sometimes soon.
