### ISSUE TITLE
How to modify background shader

### ISSUE THREAD

**Issue by joondong** [Unity-Technologies/arfoundation-samples#621]
**How to change background shader?**
I am trying to apply some filter to background of camera streaming. Kind of color filtering. 
However, whenever I changed Library/PackageCache/com.unity.xr.core@4.0.8/Assets/Shaders/ARCoreBackground.shader it returns to original code. 

Can I modify the shader?

**How to shake background texture?**
What I am trying to make is "Camera shake" which is used for bomb explosion.
In my AR apps, I need to shake background as well because shaking just rendering camera looks weird. 

How to shake background texture for this work?

**Comment by joondong** [comment]
At 0~1 sec, camera shakes but not background. 
https://youtu.be/VPq5WvGUyzU

**Comment by tdmowrer** [comment]
You can override the material (with a custom shader) instead of directly modifying the one in the package. See my comment here: https://github.com/Unity-Technologies/arfoundation-samples/issues/620#issuecomment-705027617

That video seems to have been removed, but if you want the background texture to shake, try adding a small random offset to the `gl_Vertex` in the shader, around this line:
```hlsl
// Transform the position from object space to clip space.
gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;
```

**Comment by joondong** [comment]
@tdmowrer Thanks for your help!!!!! I made it!
https://www.youtube.com/watch?v=iXWl5f_iW7k

**Comment by tdmowrer** [comment]
You'd need to change the `gl_FragColor` in the fragment shader.
