### ISSUE TITLE
[Bug] ObjDetQueue.thread crash when using Object Tracking (ARTrackedObjectManager) and AR Foundation

### ISSUE THREAD

**Issue by KirillKuzyk** [Unity-Technologies/arfoundation-samples#641]
**Unity bug report case number**
Case 1287297

**Describe the bug**
The app is crashing while using ARKit Object Tracking.
Conditions:
- Object reference library contains at least one object;
- ASSession is disabled while ARTrackedObjectManager.referenceLibrary != null, then enabled again;

**To Reproduce**
- Unzip the example project and open it in Unity;
- Switch build target to iOS;
- Build project;
- Choose your signing certificate in xCode;
- Run the app on iOS device that supports Object Tracking (iOS 12+, A9+ CPU);
- The app will crash in approximately 80% of launches;
- Please see ARFoundationObjectTrackingCrash.cs for more info;

**Expected behavior**
The app doesn't crash.

**Actual behavior**
The app is crashing in 80% of cases.
Crashes in Release configuration are less frequent than in Development Build.

**Smartphone (please complete the following information):**
 - Device: iPad Pro 2020/iPhone X
 - OS: iOS 14/iOS 13
 - Unity version: 2020.1.8/2019.4.12
 - ARFoundation version: 4.0.2/4.0.9/4.1.0-preview.11

[ARFoundationObjectTrackingCrash.zip](https://github.com/Unity-Technologies/arfoundation-samples/files/5430380/ARFoundationObjectTrackingCrash.zip)
![Screenshot 2020-10-23 at 18 02 33](https://user-images.githubusercontent.com/13222270/97022888-5f4dad00-155d-11eb-867e-eebc78002607.jpg)

**Comment by tdmowrer** [comment]
Thank you for the excellent (and minimal) repro project. I am able to reproduce this; however, the callstack is inside ARKit (on their "object detection" thread), so at the moment it appears to be an issue with ARKit. I will continue digging into it on our side, but I don't think there's much we can do to mitigate it.

In the project you've provided, you reproduce the issue by enabling and disabling the session every .33 seconds. Presumably, your "real" app isn't doing this; can you provide any more details on the situation in which you encounter this crash in the app you're working on?

**Comment by KirillKuzyk** [comment]
I was able to reproduce the crash without the ridiculous 0.33 seconds delay! ARSession should be disabled AFTER an object was successfully detected. Here is a new repro project:
[ARFoundationObjectTrackingCrash_2_0.zip](https://github.com/Unity-Technologies/arfoundation-samples/files/5445389/ARFoundationObjectTrackingCrash_2_0.zip)

I also found out that the crash is MUCH LESS frequent if 'Address Sanitiser' is enabled in xCode.

My real AR app is actually a helper app for AR Foundation Editor Remote plugin and yes, it doesn't switch ARSession.enabled so often, I just wanted to consistently reproduce the same crash in a small example. In my app, I can reproduce the crash without calling ARSession.Reset(). But in a boiled down example, the crash only occurs after ARSession.Reset(), can't figure out why. I can share the source code of my plugin with you if you think it will help you to track down the issue.

**Comment by tdmowrer** [comment]
Calling `Reset()` means that the next time the ARSession is enabled, it will reset tracking and remove existing anchors - it's the same as calling [runWithConfiguration:options:](https://developer.apple.com/documentation/arkit/arsession/2875735-runwithconfiguration) with the options [ARSessionRunOptionResetTracking](https://developer.apple.com/documentation/arkit/arsessionrunoptions/arsessionrunoptionresettracking) and [ARSessionRunOptionRemoveExistingAnchors](https://developer.apple.com/documentation/arkit/arsessionrunoptions/arsessionrunoptionremoveexistinganchors).

I've seen it crash in a few different places in on the object detection thread, so I think there is generally a race condition in ARKit related to object tracking. The reason it may be easier to reproduce in your second project is because it may be trying to update the existing [ARObjectAnchor](https://developer.apple.com/documentation/arkit/arobjectanchor?language=objc) while it is simultaneously clearing them.

The Address Sanitizer changes the way memory allocations work, so it's not surprising this would have some effect (whether positive or negative). I have also found it is much easier to reproduce in release builds than debug builds, which also affects the way memory is allocated.

Since all of the calls Unity makes to the ARSession occur on the main thread and the crash consistently happens on their object tracking thread, I'm not sure there's much we can do here. You might want to report this to Apple via their [feedback assistant](https://feedbackassistant.apple.com/).

**Comment by KirillKuzyk** [comment]
Thanks for clarifications! I'll try to reproduce the crash in a native xCode project so I can file a bug report to Apple.

No, my app doesn't update any existing ARObjectAnchor. What I think is happening is a session configuration change that leads to a call to 'runWithConfiguration:options: with the option ARSessionRunOptionResetTracking'.

Do you think ARKit Object Tracking should be part of AR Foundation while such a critical bug is present? Yes, it's a bug in ARKit itself, but Unity users still will be affected by it without a chance to make a workaround.

**Comment by tdmowrer** [comment]
> No, my app doesn't update any existing ARObjectAnchor.

Just to clarify, I was suggesting that ARKit was in the process of updating information about the object anchor (on its ObjDetQueue thread), not that you were doing anything in your app.

> What I think is happening is a session configuration change that leads to a call to 'runWithConfiguration:options: with the option ARSessionRunOptionResetTracking'.

Configuration changes to not use the `ARSessionRunOptionResetTracking` option. Only `ARSession.Reset()` does this.

**Comment by KirillKuzyk** [comment]
I have an update, maybe further information can be useful to everyone else who will encounter this issue.

The crash occurs much frequently when an async task is running. Here are the examples of async tasks I know of:

1. [XRCpuImage.ConvertAsync()](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.1/api/UnityEngine.XR.ARSubsystems.XRCpuImage.html#UnityEngine_XR_ARSubsystems_XRCpuImage_ConvertAsync_UnityEngine_XR_ARSubsystems_XRCpuImage_ConversionParams_)
2. [MutableRuntimeReferenceImageLibrary.ScheduleAddImageWithValidationJob()](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.1/api/UnityEngine.XR.ARSubsystems.MutableRuntimeReferenceImageLibrary.html#UnityEngine_XR_ARSubsystems_MutableRuntimeReferenceImageLibrary_ScheduleAddImageJob_Unity_Collections_NativeSlice_System_Byte__UnityEngine_Vector2Int_UnityEngine_TextureFormat_UnityEngine_XR_ARSubsystems_XRReferenceImage_Unity_Jobs_JobHandle_)
3. [ARKitSessionSubsystem.GetARWorldMapAsync()](https://docs.unity3d.com/Packages/com.unity.xr.arkit@2.0/api/UnityEngine.XR.ARKit.ARKitSessionSubsystem.html#UnityEngine_XR_ARKit_ARKitSessionSubsystem_GetARWorldMapAsync)

Once I have rewritten my app to wait for all async tasks to finish before resetting AR session, the crash now occurs very rarely.

**Comment by AkhilRaja** [comment]
@KirillKuzyk How did you are checking for all the async tasks to complete before resetting the AR session ? Can you please share a snippet for reference ?

I am also facing this error and lately it has increased in frequency.

**Comment by AkhilRaja** [comment]
@tdmowrer do you have any suggestions on how to go about this?

**Comment by tdmowrer** [comment]
> @tdmowrer do you have any suggestions on how to go about this?

This sounds like it needs escalation to Unity. Please open a new issue (they probably won't see / respond to this closed issue).
