### ISSUE TITLE
Map Camera Video onto 3D Face Geometry

### ISSUE THREAD

**Issue by jessekirbs** [Unity-Technologies/arfoundation-samples#657]
Hello! I'm trying to figure out is it's possible to utilize the camera feed and map that as a texture onto 3D face geometry using AR Foundation - [like at this link](https://developer.apple.com/documentation/arkit/tracking_and_visualizing_faces). Are the TrueDepth and LIDAR camera feeds available from the iPhone?

I can't find any documentation on how to do this in anything other than Swift. Any guidance would be greatly appreciated. Thank you!

**Comment by tdmowrer** [comment]
That sample uses Scene Kit, which has a utility for extracting the face geometry and material. ARFoundation lets you get the [face geometry & uv texture coordinates](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/api/UnityEngine.XR.ARFoundation.ARFace.html) and [the camera image](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.0/manual/cpu-camera-image.html), but there is no utility to combine them.

**Comment by DavidMohrhardt** [comment]
Offering up a possible solution, you could use a [grab pass shader](https://docs.unity3d.com/Manual/SL-GrabPass.html) to grab the background where the face mesh get's rendered.

**Comment by sam598** [comment]
Instead of a grab pass shader I would take the CPU camera image like @tdmowrer suggested. ARFoundationBackgroundRenderer crops the image and projection matrix to the phone screen, so this will get you the full image from ARKit.  You can create a camera projection matrix for that image using the [camera intrinsics](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@2.2/api/UnityEngine.XR.ARFoundation.ARCameraManager.html#UnityEngine_XR_ARFoundation_ARCameraManager_TryGetIntrinsics_XRCameraIntrinsics__).

The UV coordinates of the face mesh will be the screen space position of the face geometry vertices, calculated using that projection matrix. You should be able to calculate those vertices on the CPU using [MultiplyPoint](https://docs.unity3d.com/ScriptReference/Matrix4x4.MultiplyPoint.html), however it would be fastest to pass the projection matrix to a custom vertex shader and calculate the UVs there.

Keep in mind this real time method does not account for occlusion. If a face is captured from the side, the hidden part of the mesh will be a mirror image.

**Comment by jessekirbs** [comment]
Thanks for the suggestions! Will test all this out and report back.
