### ISSUE TITLE
ARFoundation not included in build with assetbundle scene (Unity beta)

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#66]
Hi, we just upgraded to the new Unity beta's to work around the freezing issues, and found the following.

The camera in the AR scene stays black (also, doesn't ask for camera permission). Upon inspecting the log we found a lot of 'monobehaviour missing' / unknown class warnings on AR camera related objects (ARSession, ARSessionOrigin). We had issues like this before when we had the option 'strip engine code' turned on, but that is not the case right now.

We have identified the issue however, it is because we only have one scene in the build (splashscreen) which downloads everything else from our server (assetbundles). If there is no arfoundation related component in the splashscreen it will be omitted from the build, and thus won't work in assetbundle scenes. Workaround right now is to attach an ARSession to the camera in our splashscreen (eventhough it's not an AR Scene).

For what its worth, this is the content of our link.xml (as generated by the plugin)

```
<linker>
  <assembly fullname="Unity.XR.ARKit" preserve="none" ignoreIfMissing="1"/>
</linker>
```

**Comment by tdmowrer** [comment]
Code stripping is always enabled when building with the IL2CPP backend. The reason for the `link.xml` is because the assemblies `Unity.XR.ARKit` and `Unity.XR.ARCore` do not contain code that is referenced by anything else (they use a `RuntimeInitializeOnLoad` to register themselves with other systems), and `preserve="none"` just forces the linker to _consider_ these assemblies (but still strip unused parts).

However, `ARSession` and `ARSessionOrigin` are part of `Unity.XR.ARFoundation` -- you don't normally need to specify this in the `link.xml` because they are normally `MonoBehaviour`s in your scene, so they would be referenced...except in your case. Try adding

```xml
  <assembly fullname="Unity.XR.ARFoundation" preserve="all" ignoreIfMissing="1"/>
  <assembly fullname="Unity.XR.ARExtensions" preserve="all" ignoreIfMissing="1"/>
```

to your `link.xml`. The `preserve="all"` will force everything in the assembly to be present. While this may be overaggressive, there's no way for the linker to know which parts of the assembly you're using since it isn't in your scene.

**Comment by nilsk123** [comment]
Thanks for the in depth explanation, will try this tomorrow. Wonder why we didn't run into this before though, even without the link.xml present at all. Using latest stable for example.

**Comment by nilsk123** [comment]
Can confirm this fixes my problem.
