### ISSUE TITLE
__arcore_education.xml: error: file not found.

### ISSUE THREAD

**Issue by Rorschach1219** [Unity-Technologies/arfoundation-samples#71]
Run the sample scenario without modifying anything, unity2018.2.16f1,11 month 29th 6 o'clock in the afternoon download the project project
![default](https://user-images.githubusercontent.com/20067002/49216226-8351f380-f405-11e8-8297-1ad3fd5d86de.png)

**Comment by tdmowrer** [comment]
The path in the stderr is `C:\Users\???????`, which is not a valid path. Does your username involve unicode or other special characters?

Are you able to build an empty scene (without the ARCore package in your project) for Android?

**Comment by SafwanCheng** [comment]
![default](https://user-images.githubusercontent.com/20067002/49264737-74f9eb00-f48a-11e8-9198-1fe823ea73a2.png)

This XML file does exist, the problem is my username, I am a Chinese, my name must be Chinese characters. How to solve this problem? I can directly modify a series of actions such as the registry may cause my computer to crash, because more than 1000 of the registry has saved my Chinese username key value pair, a new user is unlikely, because it is like a new computer, and copying data will take a lot of time to do the transfer.

![default](https://user-images.githubusercontent.com/20067002/49264907-1a14c380-f48b-11e8-9267-488383fb1ca5.png)

I removed Arcore plugin and created an empty scene. Can be output to the Android platform normally. There is no error, arcore This path problem, can add some judgment, do some conversion. or let the computer recognize this path when I compile it.

**Comment by tdmowrer** [comment]
I would not recommend altering your registry or username. This is a bit of a mystery; I tried renaming `arcore_client.aar` to `漢字.aar`, and that worked for me, so both Gradle and Unity can handle Chinese characters in path names.

That `aar` is the same one that Google distribute in their SDK for Unity. Can you try building [their sample](https://github.com/google-ar/arcore-unity-sdk) and see if you have the same problem?

**Comment by SafwanCheng** [comment]
same problem

**Comment by tdmowrer** [comment]
You might try changing the directory that Gradle uses. The default is `$USER_HOME/.gradle`, but you can set it to a different directory by setting the `GRADLE_USER_HOME` environment variable. See the [Gradle Docs](https://docs.gradle.org/current/userguide/build_environment.html) for more information.

**Comment by tdmowrer** [comment]
> ...but mistakes still appear, and they don't work.

Can you be more specific? What are the "mistakes"?

**Comment by SafwanCheng** [comment]
I migrated the .gradle directory to the D disk, then set the path in the environment variable, and when I returned to unity to compile again, there was still an error. This problem has not been solved, just because of my Chinese username.

**Comment by tdmowrer** [comment]
When I set `GRADLE_USER_HOME` to `F:\Gradle` and delete `C:\Users\[Username]\.gradle`, files are generated in `F:\Gradle`, but not `C:\Users\[Username]\.gradle` when building the Android Player from Unity. Did you restart Unity after setting `GRADLE_USER_HOME`? Does `D:\Android\gradle_repo\.gradle` remain empty, or are files written to it?

**Comment by SafwanCheng** [comment]
The problem has been solved and I have now successfully packaged an APK. Thank you for your patient answers and wish you a happy life.

**Comment by tdmowrer** [comment]
That's great! I'm glad you were able to resolve the issue. In case other people have the same problem, how did you fix it?

**Comment by SafwanCheng** [comment]
There is no doubt that if someone encounters the same problem as me and turns to me, I will certainly patiently guide and help solve the problem. I will post posts in Chinese in the domestic forum to record the problems I have encountered in the process of using the ar foundation. Thank you for your reply,Best wishes for you.
