### ISSUE TITLE
How to save all point clouds in a room and reload them next time?

### ISSUE THREAD

**Issue by peterchen2001** [Unity-Technologies/arfoundation-samples#770]
Hi experts,
I tested this AR Foundation samples app on my Andriod cellphone, the functions in this demo are very cool. I try each sample but don't find any ideas on how to save all point clouds in a room(scanned by my cellphone) and reload them next time I restart my app? Any clue to make this using AR Foundation?

**Comment by KirillKuzyk** [comment]
This task is not trivial and the closest solution to your problem is to use ARCore Cloud Anchors:
https://github.com/google-ar/arcore-unity-extensions

First, you should create Cloud Anchors. Then, you save all cloud points relative to the created Cloud Anchor so you can re-create your scene in the next session.

**Comment by peterchen2001** [comment]
Good idea, thanks a lot. I will have a try.
