### ISSUE TITLE
Light estimation: which values to use for light intensity/color

### ISSUE THREAD

**Issue by alexanderameye** [Unity-Technologies/arfoundation-samples#777]
The following light estimation variables are potentially available.

averageBrightness
averageIntensityInLumens

mainLightIntensityLumens
averageMainLightBrightness

averageColorTemperature
colorCorrection
mainLightColor

mainLightDirection
ambientSphericalHarmonics

If I have a single directional light, how do I map these values onto the light? I'm asking because I can't figure it out by looking at LightEstimation.cs and HDRLightEstimation.cs. In those scripts, you set the main light intensity to both averageBrightness and averageMainLightBrightness. You also set the light color to both colorCorrection and mainLightColor.

The mainLightDirection and ambientSphericalHarmonics values are clear, same for averageColorTemperature but it's unclear what color/intensity to use for my main light.

Which one is it? Are the parameters mutually exclusive so that either averageBrightness of averageMainLightBrightness will return null at any given time?

Any additional insights or docs would be great because this is super unclear..

**Comment by tdmowrer** [comment]
> Are the parameters mutually exclusive...?

It depends on the hardware, OS version, and features you have enabled. In general, I believe on Android they are mutually exclusive, and on iOS you'll get "average" info always and "main light" info only when in a user-facing camera mode. However, your best bet is to check which values are null, since they could potentially change with future updates to iOS.
