### ISSUE TITLE
New to AR Foundation, Can't get rid off errors.

### ISSUE THREAD

**Issue by PabloKamien** [Unity-Technologies/arfoundation-samples#779]
Hi!
I'm new to AR, and I'm following your tutorial/unity's documentation. 
But I cannot even begin, because there's 4 errors I don't know how to get rid off.
What can I do?
Thanks!!

<img width="1438" alt="Screen Shot 2021-03-29 at 14 38 34" src="https://user-images.githubusercontent.com/35156839/112880239-8fffb880-90a0-11eb-9741-8a32555696fa.png">

**Comment by tdmowrer** [comment]
These are not errors; they are warnings telling you that AR features could not be started on the current platform. It looks like you hit "play" in the Editor; since AR Foundation only works on device, the warning is telling you that the features you've requested won't be started.

Try building for iOS, Android, Magic Leap, or [Windows MR](https://docs.unity3d.com/Packages/com.unity.xr.windowsmr@5.2/manual/index.html) instead.

What tutorial or documentation were you following?

**Comment by PabloKamien** [comment]
Thanks for the clarification!!!

https://docs.unity3d.com/Manual/configuring-project-for-xr.html

https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.1/manual/index.html#basic-setup

https://www.youtube.com/watch?v=FGh7f-PaGQc&t=835s
