### ISSUE TITLE
How to not stuck objects while we are near plane or any real objects

### ISSUE THREAD

**Issue by Prashant29** [Unity-Technologies/arfoundation-samples#831]
How do I...
I am trying to view a virtual wall on my wall, but when I get closer to it, it goes freeze, and after some space and movement, it works but changed its positions.

Please consider below video and pic for reference.

Thanks
![WhatsApp Image 2021-05-29 at 2 08 43 PM](https://user-images.githubusercontent.com/19671442/121701864-f9fbfb80-caee-11eb-9620-61f5dee81f50.jpeg)

https://user-images.githubusercontent.com/19671442/121701876-fc5e5580-caee-11eb-8d40-1f18de988966.mp4

**Comment by Prashant29** [comment]
Any help or direction would be appreciated.

I'm using Unity: 2020.2.6f1
AR foundation: 4.2.0 Pre 2
XR Plugin Mangement: 4.0.1
ARCore XR Plugin: 4.2.0-pre.2

**Comment by Prashant29** [comment]
@tdmowrer

**Comment by tdmowrer** [comment]
A blank wall makes it very difficult for any AR SDK (ARCore in this case) to work out its position in the world. There needs to be some visible features that it can track from frame to frame. Wood grain, an image, or some other will help greatly.

**Comment by Prashant29** [comment]
Thanks for your reply @tdmowrer. 

Actually, I'm trying to achieve something similar to this: https://youtu.be/ErdC8kOUQN0

If any idea 💡 , how it is possible, please guide me. Thanks.

**Comment by tdmowrer** [comment]
The video appears to use ARKit. Newer iPhones have lidar sensors, which can provide better tracking data, which may explain why they have better results.

**Comment by Prashant29** [comment]
Thanks Again Tim, for reply. But I am expecting some more info if you can provide. I really need to solve this problem. 
If you can check this: https://youtu.be/NNrZRAcJrrY

This is working and Android also. I have strong feelings that this could happen with ARFoundation.

Thanks for your time. Really appreciate for help.

**Comment by Prashant29** [comment]
Actually I'm curious how they can track planes using lean their device nad touch their notch to wall. Is there any functionality in ARFoundation. 

Thanks

**Comment by tdmowrer** [comment]
In the second video, the wall has a lot of texture to it, and other objects (like the floor and door) are also visible. This makes it much easier for ARCore to track the device's pose in the world. There isn't anything you can enable in AR Foundation that will provide better device tracking; it really comes down to the environment you are in, and a large, featureless surface is a poor candidate.

>  I'm curious how they can track planes using lean their device nad touch their notch to wall.

That sounds like logic specific to their app, and I can't say how they are doing it from the video. Maybe they wait until the device is pointed down, or detect that it stops translating forward (because it hits the wall).

**Comment by Prashant29** [comment]
Thanks, Tim, For your review and suggestion.
