### ISSUE TITLE
Ability to use ARCore Playback feature in Unity Editor

### ISSUE THREAD

**Issue by LinaEagle** [Unity-Technologies/arfoundation-samples#832]
**Is your feature request related to a problem? Please describe.**
A new version of ARFoundation includes ARCore Record and Playback API, which allows you to repeat a particular AR experience. If we could run a Playback in the Unity editor, it would an extremely powerful feature for reducing development time dramatically. 

**Describe the solution you'd like**
It could be some kind of wrapper, which emulates a presence of ARCoreSessionSubsystem in the Unity Editor.

Hope you could think about it, it would be an extremely powerful tool!

**Comment by tdmowrer** [comment]
The recording feature only records sensor data; during playback, ARCore runs as normal but uses the prerecorded sensor data instead of the live data. We can't play back the session in the Editor because we'd actually have to run ARCore in the Editor.

ARKit has a similar feature (Xcode lets you specify a recording to use instead of live data) but it works in the same way -- it is only the raw sensor data and must be played back on device.

**Comment by LinaEagle** [comment]
I see, thank you for your quick response. That's a bit sad! I Hope, the new ARFoundation Remote feature, which is supposed to be in development nowadays, will help with shortening AR dev iterations.
