### ISSUE TITLE
Environment Probe Reflections are blurry on Android

### ISSUE THREAD

**Issue by RobinopdeBeek** [Unity-Technologies/arfoundation-samples#842]
The AR Environment Probe Reflections on Android are very blurry and not what you would expect. Do you also have an Android sample project where the environment reflections are working and look like actual reflections?

Unity 2020.3.8  / Android Pixel 2

**Comment by DavidMohrhardt** [comment]
Unfortunately, ARCore cube maps are not intended to be perfect reflections and instead are meant to just add some shading color detail to your AR content.

The environment cube map ARCore surfaces is generated based only on the current ARCamera background texture and is a fairly low resolution texture (16x16 per face of the cube map).

in order to accomplish a higher resolution reflection you would need to build your own cube map using the camera background texture and device orientation to stitch together a higher resolution cube map.

**Comment by RobinopdeBeek** [comment]
Thank you for your response. Then I can stop trying to figure it out and leave it as is.
