### ISSUE TITLE
Restoring ARAnchors from ARWorldMap

### ISSUE THREAD

**Issue by thePostFuturist** [Unity-Technologies/arfoundation-samples#868]
Docs for [ARWorldMap ](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/manual/anchor-manager.html) state they include saved anchors, however no literature on how to retrieve them and from where. An elaboration on how to access them would be helpful.

**Comment by tdmowrer** [comment]
From [ARKitSessionSubsystem.ApplyWorldMap](https://docs.unity3d.com/Packages/com.unity.xr.arkit@4.2/api/UnityEngine.XR.ARKit.ARKitSessionSubsystem.html#UnityEngine_XR_ARKit_ARKitSessionSubsystem_ApplyWorldMap_UnityEngine_XR_ARKit_ARWorldMap_):

> This attempts to relocalize the current session to the given worldMap. If relocalization is successful, the stored planes and anchors from the worldMap are added to the current session.

So you access anchors them in the way you normally do, i.e., by using the anchor manager. What's different is the way the anchors are added to the session: in this case, it is a side effect of loading the world map rather than adding an `ARAnchor` component to a GameObject. You do not need to retrieve them from the world map separately.

**Comment by thePostFuturist** [comment]
Thanks as always @tdmowrer
