### ISSUE TITLE
ARTrackedImage Add/Remove Behaviour

### ISSUE THREAD

**Issue by sdomenici009** [Unity-Technologies/arfoundation-samples#884]
**Unity bug report case number**
1362877

**Describe the bug**
Tracking a reference image while adding more to a library causes the ARTrackedImage tied to that reference image to be added and removed multiple times.

**To Reproduce**
1. Open up the first image in the Targets folder.
2. Build to device. (This was reproduced on both IOS and Android).
3. Click Load Images.
4. Scan the image you pulled up in (1) and see in logs that a new ARTrackedImage is added to the ARTrackedImageManager.
5. As you continue to scan the image notice in logs that as other reference images are added to the library the ARTrackedImage is removed and added multiple times.

**Expected behavior**
As you continue to scan the image notice in logs that as other reference images are added to the library the ARTrackedImage is **NOT** removed and added multiple times.

**Actual behavior**
As you continue to scan the image notice in logs that as other reference images are added to the library the ARTrackedImage is removed and added multiple times.

**Smartphone (please complete the following information):**
 - Device: Galaxy S21 Ultra 5G 
 - OS: Android Version 11
 - Unity version: 2020.3.17f1_a4537701e4ab 

AR Package Versions:
XR Plugin Management: 4.0.7
AR Foundation: 4.1.7
ARCore XR Plugin: 4.1.7
ARKit XR Plugin: 4.1.7

**Comment by ankur-unity** [comment]
Whenever a job of adding an image to a "RuntimeReferenceImageLibrary" finishes, it sets the AR session config to dirty. This triggers an update of the configuration by ARCore. ARFoundation poll every frame to see what’s in the list of tracked images by ARCore. If ARCore stop reporting on a tracked image, then ARFoundation will report it as having been removed. So, if ARCore is removing the tracked image after a configuration update triggered due to image addition then ARFoundation removes it as well.

Adding a snippet from Android Logcat for reference. Notice how "Removed: 000bb3614053f7f1b04d859088156e64" is listed after a configuration update. This behavior is govern by ARCore and not in control of ARFoundation. The issue will not appear if the scanning of an image is done after all the images are done loading.

```
4475 5918 Verbose Unity-ARCore Configuration will be updated with these features enabled:
4475 5918 Verbose Unity-ARCore RearCamera
4475 5918 Verbose Unity-ARCore PositionAndRotation
4475 5918 Verbose Unity-ARCore ImageDetection
4475 5918 Verbose Unity-ARCore AutoFocus
4475 5918 Verbose Unity-ARCore OnBeforeSetConfiguration
4475 5918 Verbose Unity-ARCore AugmentedImageDatabase: 0xb400007745580350
4475 5918 Verbose Unity-ARCore LightEstimationMode: 0
4475 5918 Verbose Unity-ARCore PlaneFindingMode: 0
4475 5918 Verbose Unity-ARCore UpdateMode: 0
4475 5918 Verbose Unity-ARCore FocusMode: 1
4475 5918 Verbose Unity-ARCore AugmentedFaceMode: 0
4475 5918 Verbose Unity-ARCore DepthMode: 0
4475 5918 Verbose Unity-ARCore InstantPlacementMode: 0
4475 5918 Info native I1117 22:04:30.326650 5918 session.cc:559] Session::CheckAndWriteCurrentConfig returning OK.
4475 5918 Warn Unity Removed: 000bb3614053f7f1b04d859088156e64
4475 5918 Warn Unity ARController:OnTrackedImagesChanged(ARTrackedImagesChangedEventArgs)
4475 5918 Warn Unity System.Action`1:Invoke(T)
4475 5918 Warn Unity UnityEngine.XR.ARFoundation.ARTrackedImageManager:OnTrackablesChanged(List`1, List`1, List`1)
4475 5918 Warn Unity UnityEngine.XR.ARFoundation.ARTrackableManager`5:Update()
```
