### ISSUE TITLE
Is image tracking work on captured image ?

### ISSUE THREAD

**Issue by hardybbs123** [Unity-Technologies/arfoundation-samples#891]
I just made a test .
1. I take capture of book cover use CPUImage example.
  `  image.Convert(conversionParams, new IntPtr(rawTextureData.GetUnsafePtr()),rawTextureData.Length);, `
2. then I add capture image at runtime with` mutableLibrary.ScheduleAddImageWithValidationJob. `
3. but I found it can not be reconginzed.
why this happen?  I had made it in front view capture .   
I put changed code  [ https://github.com/hardybbs123/artest ](url)  based Image tracking scene.

**Comment by ankur-unity** [comment]
Can you check if the Texture that you're importing has the correct NPOT setting or not? It should be set to "None" instead of the default value. Otherwise, the aspect ratio could be altered causing issues with the platform providers. See https://github.com/Unity-Technologies/arfoundation-samples/issues/783#issuecomment-812510909.

**Comment by hardybbs123** [comment]
> Can you check if the Texture that you're importing has the correct NPOT setting or not? It should be set to "None" instead of the default value. Otherwise, the aspect ratio could be altered causing issues with the platform providers. See [#783 (comment)](https://github.com/Unity-Technologies/arfoundation-samples/issues/783#issuecomment-812510909).

m_CameraTexture = new Texture2D(image.width, image.height, format, false);    yes,here  false means  NPOT
