### ISSUE TITLE
[Bug]Ar foundation Image Tracking Is not working Properly ..!!

### ISSUE THREAD

**Issue by Ahmadhumayoun** [Unity-Technologies/arfoundation-samples#899]
Hey
I have added Around 25 Images in Refrence Library...!!
As per my client requirement..!!
But it is tracking the wrong images ..!!
really frustrating ..
I have [been](url) working on this issue from around 2 weeks..!!

Main Issue that..!!
it detect the image
and then instantiate the wrong prefab..!!

Now I have a text on screen which shows the name of targeting image...!!
and It show the name of that image wrong..!!
Compeletly wrong..!!
[ImageTrackerManager.Docx](https://github.com/Unity-Technologies/arfoundation-samples/files/7443320/ImageTrackerManager.Docx)

I have double check the name in reference library and other stuff..!!

here is my script down there..!!``

**Comment by DavidMohrhardt** [comment]
It sounds like what you are seeing is that the library itself picks up images just fine but it doesn't display the right content when you do.  This is likely an issue with the `Dictionary` keys you are using.  You may find more help posting on our forums: https://forum.unity.com/forums/ar.161/

Otherwise, please log a bug at https://unity3d.com/unity/qa/bug-reporting using the following template and post the case number here.

```
**Unity bug report case number**
Please log a bug at https://unity3d.com/unity/qa/bug-reporting and post the case number here.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Actual behavior**
A clear and concise description of what actually happened.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13]
 - Unity version
 - ARFoundation version
```
