### ISSUE TITLE
Image tracking: how to remove content when object is out of sight

### ISSUE THREAD

**Issue by shacharoz** [Unity-Technologies/arfoundation-samples#902]
I have used the sample of a single or multiple image trackers.
I created an app that has several objects and ar trackers. 
It works.

But the issue is that when I leave the marker, the object stays alive. I would like it to be removed. 

I tried using a listener to the event, but perhaps I am doing it wrong.
Do you have a best practice for this ?

**Comment by ankur-unity** [comment]
You can listen to the [OnTrackablesChanged](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/api/UnityEngine.XR.ARFoundation.ARTrackableManager-5.html#UnityEngine_XR_ARFoundation_ARTrackableManager_5_OnTrackablesChanged_List__4__List__4__List__4__) of the ARTrackables and disable them when they are out of the camera frustum.  You can also destroy the content that you have instantiated under the ARTrackable game object.  You should not destroy the trackable objects created by AR Foundation since they are being tracked by the subsystem.  See [trackable-managers](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/trackable-managers.html#adding-and-removing-trackables).

**Comment by shacharoz** [comment]
Its kind of what I did, and it didnt work correctly.
I will put some code soon.

**Comment by shacharoz** [comment]
managed to solve it. i will put a code example soon online

**Comment by 9990sherry** [comment]
> 

Hi I am facing the same issue. Did you get it work? Do you have the sample code? Thank you so much.
