### ISSUE TITLE
how to release memory of ARTrackedImageManager's RuntimeReferenceImageLibrary

### ISSUE THREAD

**Issue by hardybbs123** [Unity-Technologies/arfoundation-samples#912]
I add 100 images into RuntimeReferenceImageLibrary with  mutableLibrary.ScheduleAddImageWithValidationJob
 .
but if I change ReferenceImageLibrary with below code , it seem memory not release . 
```
var manager = transform.parent.parent.GetComponent<ARTrackedImageManager>();
        if (manager != null)
        {
            manager.enabled = false;
            var lib = firstLibrary;
            manager.referenceLibrary = manager.CreateRuntimeLibrary(lib);
            manager.enabled = true;
            print("trun off referenceLibrary");
        }
        GC.Collect();
        GC.WaitForPendingFinalizers();
        GC.Collect();
```
or 

how to release RuntimeReferenceImageLibrary ?

I am using Unity 2020.3 LTS. AR foundation 4.2 .with android 11 ,RedMI 8note pro.
BTW I use ` systemMemoryRecorder = ProfilerRecorder.StartNew(ProfilerCategory.Memory, "System Used Memory");` to monitor memory.

**Comment by hardybbs123** [comment]
I found ARTrackedImageManager 
`Dictionary<Guid, XRReferenceImage> m_ReferenceImages = new Dictionary<Guid, XRReferenceImage>();`
it only add record list never remove, means if you change scene, reference counter >0 will forbid system GC collect memory.
I also can not change this class ARTrackedImageManager.cs , what a pity!!!

**Comment by ankur-unity** [comment]
Clearing the dictionary will not have a significant impact on the memory since it's just storing a guid and an instance of `XRReferenceImage` struct. Both of which takes few bytes of memory.

How are you creating the `RuntimeReferenceImageLibrary`? Are you using `Texture2D` at runtime to add to the reference library?

**Comment by ankur-unity** [comment]
Final remark: Most probably the memory is occupied by the `Texture2D` objects that is used to create the `XRReferenceImageLibrary`. AR Foundation doesn't manage the memory of user created object, so the memory used by the Texture2D can be safely released by the user once the scheduling job is finished.

Closing this thread due to inactivity.
