### ISSUE TITLE
 Crashes on iOS when reset AR

### ISSUE THREAD

**Issue by Leiong** [Unity-Technologies/arfoundation-samples#99]
Crash on iOS when resetting AR ,
`void ResetAR()
    {
        session.Reset();
    }`,
sometimes turning off AR will also cause crash。
Xcode prompt warning as shown below：
![fafdafasfsfaf](https://user-images.githubusercontent.com/41097890/53139685-69b7e680-35c5-11e9-9a41-9e086859201c.png)

**Comment by nilsk123** [comment]
Probaby same as this #95

**Comment by Leiong** [comment]
> 可能与[＃95](https://github.com/Unity-Technologies/arfoundation-samples/issues/95)相同[](https://github.com/Unity-Technologies/arfoundation-samples/issues/95)

@nabiber Hi，Have you solved this problem?

**Comment by Leiong** [comment]
> 可能与[＃95](https://github.com/Unity-Technologies/arfoundation-samples/issues/95)相同[](https://github.com/Unity-Technologies/arfoundation-samples/issues/95)

@nilsk123  Hi，Have you solved this problem?

**Comment by 7891liang** [comment]
2018.3.6
same

**Comment by ROBYER1** [comment]
Since nobody else bothered to do it, I have reported this issue being caused by MultiThreaded Rendering at Unity Bug: IN-35599 - [AR Foundation] MultiThreaded Rendering crash AR Foundation when enable/disable AR Session on iOS+Android

Forum post: https://forum.unity.com/threads/multithreaded-rendering-crash-ar-foundation-when-enable-disable-ar-session.1413507/
